### ISSUE TITLE
Dependency jean85/pretty-package-versions

### ISSUE THREAD

**Issue by alksily** [getsentry/sentry-php#1035]
Version 1.4+ required Composer 2.0.

Please remove the dependency on the newer version:
```
"jean85/pretty-package-versions": "^1.2.0",
```

Error when installing:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- Installation request for jean85/pretty-package-versions 1.4.0 -> satisfiable by jean85/pretty-package-versions[1.4.0].
- jean85/pretty-package-versions 1.4.0 requires composer-runtime-api ^2.0 -> no matching package found.
Problem 2
- jean85/pretty-package-versions 1.4.0 requires composer-runtime-api ^2.0 -> no matching package found.
- sentry/sentry 2.4.0 requires jean85/pretty-package-versions ^1.2 -> satisfiable by jean85/pretty-package-versions[1.4.0].
- Installation request for sentry/sentry 2.4.0 -> satisfiable by sentry/sentry[2.4.0].
```

**Comment by ste93cry** [comment]
This is a duplicate of #1008. Please ensure that you are using the latest Composer version, and if the problem is solved feel free to close this issue

**Comment by alksily** [comment]
it's silly to do this, I can’t update the version on travis-ci, because of this, every build is considered broken.

**Comment by Jean85** [comment]
Yes you can, with `composer self-update`.

Anyhow, now the dependency has a 1.5 version that reverted that decision, see https://github.com/Jean85/pretty-package-versions/issues/21

**Comment by alksily** [comment]
In Sentry, you are not using package version >1.2, so why not fix this in the list of dependencies?
Laziness and excuses.

**Comment by ste93cry** [comment]
>In Sentry, you are not using package version >1.2

If I understand correctly, you are criticizing the fact that because we don't use any of the features (yet, at least) available in a version greater than `1.2` we should not support them, which makes no sense

>Laziness and excuses.

I'm sorry if you feel we are lazy, but the fact that you cannot/don't know how to update your own Composer version (which btw solves this issue) is not our fault

**Comment by alksily** [comment]
Pff, are you serious?
Because of your laziness, I should make changes on all my production servers? You are a cheerful guy!

**Comment by alksily** [comment]
I just asked you to fix it.
The question is closed.

**Comment by ste93cry** [comment]
So let me understand: because of your laziness in updating the package manager you use daily on your production server that fixes this exact issue, we should lock the version of a dependency so that if someone else requires a package requiring depending on a newer version he cannot install it because of us and if a bug is fixed in a newer version he won't be able to get it. It definitely makes sense and I'm a cheerful guy 😆 

>I just asked you to fix it.
>The question is closed.

You're right, question is closed because the fix is to update Composer. Cheers!

**Comment by Jean85** [comment]
@alksily please refrain from this kind of responses, they're aggressive and not deserved.

We're OSS maintainers, we do not get paid to do this and we're helping you out of our free time; it's evident that the issue is on your side, and we helped you anyway.

Now fix it on your side.

**Comment by alksily** [comment]
I'm not as aggressive as confused. Sorry if I hurt you (@Jean85 @ste93cry).
It will take a long time to fix. In my practice: it’s better to wait some time than to fixs problems that have arisen.
