### ISSUE TITLE
Sentry trace Serializer issue

### ISSUE THREAD

**Issue by luckyraul** [getsentry/sentry-php#1112]
sentry/sentry  sdk 2.4.1

Hi guys,

We create a magento sentry integration. It works well, except in this scenario. 

It requires Magento 2 knowledge

In sentry I see issue with such a name
```Cannot declare class Vendor\Customer\Plugin\Api\CustomerRepositoryPlugin, because the name is already in use```

Inside issue in the message there is a actual exception message. No real Exception trace, just trace about class redeclare.

```
 in include called at /var/www/magento/releases/20201001162424/vendor/composer/ClassLoader.php (444)
 in Composer\Autoload\includeFile called at /var/www/magento/releases/20201001162424/vendor/composer/ClassLoader.php (322)
 in Composer\Autoload\ClassLoader::loadClass called at ? (?)
 in spl_autoload_call called at ? (?)
 in is_callable called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Serializer/AbstractSerializer.php (102)
 in Sentry\Serializer\AbstractSerializer::serializeRecursively called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Serializer/AbstractSerializer.php (110)
 in Sentry\Serializer\AbstractSerializer::serializeRecursively called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Serializer/RepresentationSerializer.php (21)
 in Sentry\Serializer\RepresentationSerializer::representationSerialize called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Stacktrace.php (177)
 in Sentry\Stacktrace::addFrame called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Stacktrace.php (102)
 in Sentry\Stacktrace::createFromBacktrace called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/EventFactory.php (149)
 in Sentry\EventFactory::addThrowableToEvent called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/EventFactory.php (110)
 in Sentry\EventFactory::create called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Client.php (183)
 in Sentry\Client::prepareEvent called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Client.php (118)
 in Sentry\Client::captureEvent called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/Client.php (110)
 in Sentry\Client::captureException called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/State/Hub.php (132)
 in Sentry\State\Hub::captureException called at /var/www/magento/releases/20201001162424/vendor/mygento/module-sentry/Model/SentryHandler.php (285)
 in Mygento\Sentry\Model\SentryHandler::Mygento\Sentry\Model\{closure} called at /var/www/magento/releases/20201001162424/vendor/sentry/sentry/src/State/Hub.php (87)
 in Sentry\State\Hub::withScope called at /var/www/magento/releases/20201001162424/vendor/mygento/module-sentry/Model/SentryHandler.php (289)
 in Mygento\Sentry\Model\SentryHandler::write called at /var/www/magento/releases/20201001162424/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php (39)
 in Monolog\Handler\AbstractProcessingHandler::handle called at /var/www/magento/releases/20201001162424/vendor/monolog/monolog/src/Monolog/Logger.php (344)

```

AbstractSerializer.php somehow recreates plugin class

**Comment by stayallive** [comment]
I want to start by saying I have no Magento knowledge at all!

We use `is_callable` which in turn asks the autoloader to autoload the class if it doesn't already exists. This seems to be the fault of the autoloader trying to load an already loaded class.

This can have multiple reasons, and you should try and see if any of them are happening, I don't think this is a direct bug in Sentry.

You can check:

- If there is indeed 1 file which defines `Vendor\Customer\Plugin\Api\CustomerRepositoryPlugin`
- Check if the file has the correct casing (correct upercase and lowercase letters) in the path, this is a common issue on Linux (when developing on OSX) where a rename messes up a path, for example it was created like: `Customer\Plugin\Api\CustomerrepositoryPlugin.php` but the class itself is called `CustomerrepositoryPlugin`, on OSX this is no issue but on Linux this becomes an issue and could confuse the autoloader in loading the file twice.

Again I don't think Sentry directly causes this issue but shines light on the issue but this will require a bit if work on your side to validate 😄

**Comment by luckyraul** [comment]
File definitely is 1 only, in CorrectCase. I'll try to provide more information about autoloading. This can be a Magento issue.

**Comment by stayallive** [comment]
You could check and search the `/var/www/magento/releases/20201001162424/vendor/composer/ClassLoader.php` file, it should list the class it's loading but possibly it's duplicated in that file for some reason.

**Comment by luckyraul** [comment]
We spent time digging this problem and found the root cause

**Comment by spaceemotion** [comment]
I would like to add that we've just run into the same issue in a legacy project with Yii 1's autoloader. we got a call to `queryInternal('fetchAll', [7, 0], [])` in which `is_callable` is checking against the `[7, 0]` argument.

This creates a new exception, as a the file/class "7.php" obviously does not exist.

**Comment by ustramooner** [comment]
I can reproduce with Yii 1 as well. This only happens when running from the command line, and for some reason thinks that 'runJob.php' which is related to the entry point name is callable.

ErrorException: Warning: include(runJob.php): failed to open stream: No such file or directory
#19 /protected/yii-1.1.22.bf1d26/framework/YiiBase.php(463): include
#18 /protected/yii-1.1.22.bf1d26/framework/YiiBase.php(463): YiiBase::autoload
#17 [internal](0): spl_autoload_call
#16 [internal](0): is_callable
#15 /vendor/sentry/sentry/src/Serializer/AbstractSerializer.php(102): Sentry\Serializer\AbstractSerializer::serializeRecursively
#14 /vendor/sentry/sentry/src/Serializer/RepresentationSerializer.php(21): Sentry\Serializer\RepresentationSerializer::representationSerialize
#13 /vendor/sentry/sentry/src/FrameBuilder.php(200): Sentry\FrameBuilder::getFunctionArguments
#12 /vendor/sentry/sentry/src/FrameBuilder.php(88): Sentry\FrameBuilder::buildFromBacktraceFrame
#11 /vendor/sentry/sentry/src/StacktraceBuilder.php(66): Sentry\StacktraceBuilder::buildFromBacktrace
#10 /vendor/sentry/sentry/src/StacktraceBuilder.php(46): Sentry\StacktraceBuilder::buildFromException
#9 /vendor/sentry/sentry/src/Client.php(304): Sentry\Client::addThrowableToEvent
#8 /vendor/sentry/sentry/src/Client.php(218): Sentry\Client::prepareEvent
#7 /vendor/sentry/sentry/src/Client.php(150): Sentry\Client::captureEvent
#6 /vendor/sentry/sentry/src/Client.php(140): Sentry\Client::captureException
#5 /vendor/sentry/sentry/src/State/Hub.php(138): Sentry\State\Hub::captureException
#4 /vendor/sentry/sentry/src/functions.php(40): Sentry\captureException
#3 /protected/components/ErrorHandler.php(15): ErrorHandler::handleException
#2 /protected/yii-1.1.22.bf1d26/framework/base/CErrorHandler.php(131): CErrorHandler::handle
#1 /protected/yii-1.1.22.bf1d26/framework/base/CApplication.php(750): CApplication::handleException
#0 [internal](0): null

**Comment by etolstikov** [comment]
Same issue in my project, array with two elements trying to chech for callable method, which failed in Yii 1

**Comment by Jean85** [comment]
The stacktrace from https://github.com/getsentry/sentry-php/issues/1112#issuecomment-763200161 makes evident that the issue is in `is_callable` triggering `YiiBase::autoload`. This confirms my suspicion that the issue is in the autoloader.

We could silence errors coming from that call, but I would accept a fix like that only with a proper test, and I can't imagine how to (temporarily) mangle the autoloader in our test suite to do that.

**Comment by etolstikov** [comment]
Maybe as a solution use is_callable() with  $syntax_only = true and class_exists() with $autoload = false before testing array for callable.

**Comment by Jean85** [comment]
That would probably reduce the efficacy of the serialization though.

**Comment by etolstikov** [comment]
Even if that class not loaded (what I can not imagine because it appears in backtrace args) the information about arg ['class', 'method'] more usable than fatal error in application while trying to load class

**Comment by Jean85** [comment]
I was suggesting a mere
```php
if (! @\is_callable(...)) {
```
as a fix; I'm just worried about how to add a test against this issue in our test suite.

**Comment by Jean85** [comment]
I got my hands dirty with the autoloader in #1276 and probably fixed it!

**Comment by etolstikov** [comment]
Still reproduced. Same check in serializeValue() without handling exception
