### ISSUE TITLE
Truncate large variables in stack traces, currently it results in 413 Request entity too large 

### ISSUE THREAD

**Issue by svoss** [getsentry/sentry-php#1114]
Some code I was trying to debug that resulted in an exception wasn't send to sentry because there was a very large array in the stack trace. Sentry will return a 413 Request entity too large status code on the api call, when request body is larger than 100KB. Wouldn't it be better if the stack trace would be truncated when this happens?

Used version is 2.5.0.

Reproduction sample code:

```php
<?php
Sentry\init(
    [
        'dsn' => 'xxx',
        'environment' => 'reproduce-me'
    ]
);

$largeArray = true;

function throwError($array)
{
    throw new RuntimeException('Something went wrong with this array');
}

$repetition = $largeArray ? 100000 : 100;

$array = array_fill(
    0,
    $repetition,
    array_fill(0, 10, random_bytes(10))
);

$kb = memory_get_usage()/ 1000;
echo "$kb KB";

throwError($array);
```

**Comment by svoss** [comment]
Seems to be solvable with the maxValueLength option, but can't find this anywhere in the documentation?

**Comment by Jean85** [comment]
That's one of the basic options of this SDK (but it's specific to PHP); but you're right, it seems that it's not documented!

https://github.com/getsentry/sentry-php/blob/25a90d4215b86aa71ff3f71054ffe736313bcc20/src/Options.php#L534-L539

**Comment by LouisTSpi** [comment]
Reusing this old thread because we encountered the same limitation as described in the post: events which include large local variables such as big arrays are not ingested by sentry due to size limits. 
However the proposed solution of configuring `max_value_length` is not really a solution because it only applies to strings, not arrays or objects.

To ensure all exceptions are ingested in sentry, we implemented a `before_send` method which replaces large arrays/objects with a short string representation (such as `'<Array: 123 items, 456 bytes>'`).

We were surprised that there is no built-in mechanism to trim large non-string variables and ensure associated events are not silently dropped.
Is this something planned? And if not, why not?

Thanks in advance.

(using sentry-php 4.9.0 via sentry-symfony 5.0.1)
