### ISSUE TITLE
Try to stringify params' objects in trace

### ISSUE THREAD

**Issue by dakur** [getsentry/sentry-php#1121]
## Summary

There are listed parameters of method in trace which in case of value objects could be stringified (using `__toString()` if available) to see the actual value. E.g. in the case of screenshot below there could be something like `Object ...\CampaignId — string representation: c9443d22-5ca3-4a16-a246-b97af1aaef91`

## Motivation

It makes orientation and debugging easier.

## Additional Context

![image](https://user-images.githubusercontent.com/9862581/90510117-ae8cf100-e15a-11ea-90d1-5e5e3d6efa00.png)

**Comment by stayallive** [comment]
We have an option for that so you can implement this yourself, once we have the `Stringable` interface in PHP 8.0 we might want to implement this for `__toString` inside the SDK but for now we have the `class_serializers` option where you can implement this yourself. I think in the new docs this option got lost in conversion but a quick summary:

```php
    'class_serializers' => [
        Some\Class\Or\Interface::class => function (Some\Class\Or\Interface $object): ?array {},
    ],
```

If you return `null` it will do nothing but if you return an array that data will be shown in Sentry instead of the `Object Some\Class\Or\Interface` string.

This works with `instanceof` so you can add parent classes to `class_serializers` and serialize all child classes using that code.

Let me know if that helps, I'll try and find out where the docs went missing and bring them back 👍

**Comment by dakur** [comment]
@stayallive OK, thanks. Where should I put it? Into options array for `\Sentry\init()` function?

**Comment by dakur** [comment]
Yeah, it [looks like](https://github.com/getsentry/sentry-php/blob/2.4.3/src/Options.php#L831). Should I close this now or you want to keep it open for PHP 8.0 `Stringable`?

**Comment by stayallive** [comment]
I'd say let's close it for now if that's okay with you and once PHP 8 is here we see if there is interest to add this as a default serializer.

And yes, `$options` in `init` is the correct place for this.

**Comment by dakur** [comment]
I can not think of case why should not I want a stringifiable object to get stringified to better understand *where* the problem happened. Maybe some security issues? 🤷‍♂️

Thank you very much for your replies!

**Comment by Jean85** [comment]
Stringing an object could lead to unintended performance issues; Drupal had one big issue like that when Symfony started casting one of its object into string in form handling.

**Comment by dakur** [comment]
I've noticed, just for the record, that there is also [`Sentry\Serializer\SerializableInterface`](https://github.com/getsentry/sentry-php/blob/3.4.0/src/Serializer/SerializableInterface.php) which can be implemented to achieve the same goal. 👍
