### ISSUE TITLE
[PHP-SDK]Lantences without new element

### ISSUE THREAD

**Issue by dutom007** [getsentry/sentry-php#1131]
Hi,

I init Sentry like that :

require_once '/****/vendor/autoload.php';
Sentry\init(['dsn' => 'https://******.ingest.sentry.io/5509806','error_types' => E_ERROR ]);

If I change 'error_types' => E_ERROR to 'error_types' => E_ERROR|WARNING only my homepage, only on my ip take 8s more to get the first octet. 
But I have nothing new on Sentry panel.

I don't understand why.

**Comment by stayallive** [comment]
Hi @dutom007, just be be sure, you said you changed `error_types` to `E_ERROR|WARNING` is that an typo or did you change it correctly to `E_ERROR|E_WARNING` otherwise you might be generating some notices about `WARNING` not being defined.

Generally I would expect the request time to increase if lot's of errors are generated by Sentry, it's possible they are not sent to Sentry or accepted by Sentry for some reason.

Did you receive errors in Sentry before this change?

**Comment by dutom007** [comment]
Hi,

Yes sorry it's E_WARNING. Write too fast... 

I receive error without problem... The delay are only at work office... So strange :/

**Comment by stayallive** [comment]
That might not be too strange, I assume you have Sentry installed on you local environment and that's why the delay is only at work because possibly you have a corporate firewall blocking the requests to Sentry?

**Comment by ste93cry** [comment]
Given that no answer has been given I consider the issue solved. Feel free to reopen if that's not the case and you still need help
