### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by W0rma** [getsentry/sentry-php#1136]
This package can currently only installed using PHP 7.2, 7.3 or 7.4.

**Comment by Jean85** [comment]
This is already being addressed in #1087

**Comment by BenMorel** [comment]
When can we expect a release compatible with PHP 8?
We'd love to upgrade our app to PHP 8, but Sentry is currently preventing us from upgrading.

**Comment by ste93cry** [comment]
To be honest, I have no clue. I could lie and say in a few days, in a week, but the reality is that there is still some work to do because one of the tests is failing and the CI is broken and I think that we should not release until everything is green, even if the test is broken apparently just because of Xdebug. This is just my opinion of course, and other maintainers may disagree and decide to release anyway since everything else seems now to be compatible and fine

**Comment by BenMorel** [comment]
What about tagging a beta release then? At least people can start using it with PHP 8 right now, explicitly opting for a beta so at their own risk. And once CI is green, release the actual version.

**Comment by ste93cry** [comment]
>What about tagging a beta release then?

That may be an idea, but since we plan in a way or another to release the next week I don't think it will be necessary. We validated that switching to GitHub Actions and PCOV solves all issues we are having, so I want to wait just a few days of the next week to see if the situation on Travis improves and then I will step back and agree with the switch.

**Comment by BenMorel** [comment]
Thank you for [3.1.1](https://github.com/getsentry/sentry-php/releases/tag/3.1.1)! 🎉
This issue can be closed now.

**Comment by ste93cry** [comment]
Version compatible with PHP 8 has been released 😃
