### ISSUE TITLE
HTTP request context not sent to Sentry

### ISSUE THREAD

**Issue by rask** [getsentry/sentry-php#1147]
PHP 7.4, Sentry lib 2.x, and we are running on the hosted Sentry SaaS service. Inside Sentry I've disabled all data scrubbing (for now). The application is running with PHP-FPM in a docker-compose environment.

When I dispatch caught exceptions from our application using the PHP library, we get events properly into Sentry, but there is absolutely nothing that resembles HTTP request data visible in the UI. This presumably means that the client is not sending that data, as I have disabled all scrubbers and so on.

I initialize Sentry as follows:

```php
function get_sentry_config() : array
{
    $dsn = getenv('SENTRY_DSN');
    $env = getenv('SENTRY_ENV');
    $release = getenv('SENTRY_RELEASE');

    return [
        'dsn' => $dsn === false ? null : $dsn,
        'environment' => $env === false ? null : $env,
        'release' => $release === false ? null : $release,
        'default_integrations' => true,
    ];
}

$client = \Sentry\ClientBuilder::create(get_sentry_config());

// $client then gets passed into a logger instance thingy and so on
```

(Notice the specific `default_integrations` value which should enable `RequestIntegration` from my understanding.)

Then in my application error handling logic I use

```php
assert($exception instanceof \Throwable);

$client->captureException($exception);
```

After these I get events into Sentry, but the events are missing all information that `RequestIntegration` should provide me with: method, URI, params, etc. I do see the values for environment, PHP version, SDK version, and release properly.

Without this the integration is kinda useless when debugging anything other than language level errors.

Any ideas whether this is related to my config/setup or some setting over at the Sentry SaaS which results in this behavior?

I can't upgrade to 3.0 just yet due to conflicting dependencies.

**Comment by ste93cry** [comment]
It looks like you forgot to enable the `send_default_pii` option. Without enabling it, nothing except the request URL and method is sent. However, if what you are missing is the request body, there is a known bug that got fixed recently and the release that fixes it will came in the next days

**Comment by rask** [comment]
@ste93cry thanks.

I see no request method or URL in Sentry either. I'm still on 2.5.0 due to other dependencies, not 3.0. Does that request body bug affect 2.5 as well?

I'll try and see what happens if I enable the `send_default_pii` option.

**Comment by ste93cry** [comment]
>Does that request body bug affect 2.5 as well

Yes, but it should affect only the request body. Anyway, I think I got what's happening, taking as assumption that the code you wrote above is complete in regards to the initialization of the SDK: you are creating the client instance manually, but I cannot see that you bind it to any hub. When you call `captureException()`, under the hood all integrations run. However, the integration has to know if it's enabled for the client bound to the hub that it's being used in that moment, so it calls [`SentrySdk::getCurrentHub()->getIntegration()`](https://github.com/getsentry/sentry-php/blob/ad5d7dee50af1ec6f42912eac0860b61977250e2/src/Integration/RequestIntegration.php#L83) that returns `null` because there is no client bound and the integration is just skipped. I don't know the reasons about why you initialize the client yourself, but if you don't have to customize things like the transport or the serializer I suggest to stick with the [recommended way](https://docs.sentry.io/platforms/php/#configure) which is to call `Sentry\init()`

**Comment by rask** [comment]
Aaaaah that fixed it.

I did already call `\Sentry\init(...)` in my "bootstrap" code which is run straight after `index.php`, but did not realize that the `Hub` system works like that in the background, and attempted to just create a new client elsewhere using the same config.

So I got it working now "as expected". Instead of

```php
$client = \Sentry\ClientBuilder::create(get_sentry_config());
```

I now have

```php
\Sentry\init(get_sentry_config());

// ...

$hub = SentrySdk::getCurrentHub(); // $hub is now the instance I pass into loggers and whatnot

// and to do stuff elsewhere:

assert($exception instanceof \Throwable);

$hub->captureException($exception);
```

Thanks!

I did notice that there is little to no documentation on going at this the other way (not using `init()`), or is there? Is the global state of hubs the only way to go about using Sentry properly?

**Comment by ste93cry** [comment]
>I did notice that there is little to no documentation on going at this the other way (not using init()), or is there?

Since the recommended way is to stick with how the Unified API works, the only documentation I know that gives at least an overview of how all the architecture works can be found [here](https://develop.sentry.dev/sdk/unified-api/)

>Is the global state of hubs the only way to go about using Sentry properly?

Since everything it somehow tied with the global state, I would say yes. Nothing prevents you from using the client directly, but integrations and everything else won't function properly and this is a choice driven by the architecture of the Unified API
