### ISSUE TITLE
No errors reporting

### ISSUE THREAD

**Issue by brandinarsenault** [getsentry/sentry-php#1157]
Hi everyone,

I've been using Sentry On-Premise for awhile now, and as of recent all of my PHP applications stop working. I decided to upgrade Sentry, and it broke everything - so I thought I'd rollback to using Sentry Cloud instead. I've received 1 error (8 events) in my dashboard in the past 3 days, when I'm certain there's been more. So I took to my localhost environment to test this more, and I'm using both the test throw case in the README and generating my own sets of errors, and nothing is appearing in Sentry. Here is a screenshot of all of the errors you can see are certainly being generated:
![image](https://user-images.githubusercontent.com/15201621/103157901-78a5ec00-478e-11eb-8547-5eb11331ab75.png)

I'm initializing Sentry in a file that is included before any of this code is ran, and this worked for awhile without issues:
![image](https://user-images.githubusercontent.com/15201621/103157911-9a9f6e80-478e-11eb-8189-f5051a0e2bfb.png)

I'm struggling to see a good way to debug this issue. I'm currently using the latest version of Sentry SDK (3.1.1). Any thoughts or help would be appreciated so I can try to resolve this!

Brandin.

**Comment by stayallive** [comment]
As long as your are local the easiest debugging method is to find the `HttpTransport.php` file in your `vendor` folder and dump out a possible error thrown there: https://github.com/getsentry/sentry-php/blob/9f734af4ce8fb8ee45723cdfe9a5f633774a6373/src/Transport/HttpTransport.php#L111-L118.

Using the `ClientBuilder` class you can also set a custom logger to log transport errors to somewhere in case you need to debug this in production.

Experience tells me this is most likely an issue with the missing or invalid setting for `curl.cafile` which is a common problem on windows unfortunately and out of our hands. There are many guides online how to fix that value if it turns out the be the issue.

Another easy thing to test is to remove your `isLocalhost()` check in case that is not working properly.

Also make sure your Sentry subscription is not over the event limit because that will also drop all new events 😄 

Hope this helps get the debugging started, let us know how it goes!

**Comment by ste93cry** [comment]
I'm closing this due to lack of feedback, feel free to re-open it if you have more details to share and are still interested in it.

**Comment by thomas-saigne** [comment]
Hello,

I've got the following issue, due to the curl.cafile on windows...
So I found 2 solutions with this article ([https://php.watch/articles/php-curl-windows-cainfo-fix](https://php.watch/articles/php-curl-windows-cainfo-fix))
1- Tell cURL to parse the system certificate store : `curl_setopt($ch, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);` (seems pretty good 😃 )
2- Get and maintain my own curl.cafile on my project (seems pretty painfull 😢 )

But I can't change the option in curl since it's in the Sentry sdk.
`vendor/sentry/sentry/src/HttpClient/HttpClient.php::sendRequest`
In the original article, they give the full if to do it properly, but it could also be an option as the httpSslVerifyPeer ?
`if (defined('CURLSSLOPT_NATIVE_CA') && version_compare(curl_version()['version'], '7.71', '>=')) {`
`    curl_setopt($ch, CURLOPT_SSL_OPTIONS, CURLSSLOPT_NATIVE_CA);`
`}`

Could you have a look please ? Thanks !
