### ISSUE TITLE
Body is not sent to Sentry on large file uploads

### ISSUE THREAD

**Issue by Starfox64** [getsentry/sentry-php#1168]
When an error occurs during a "large" file upload, the body is excluded as per the `max_request_body_size` option because the file's size is included in the body size, despite not being actually sent along the form data.
https://github.com/getsentry/sentry-php/blob/e9b2d45b248d75f4c79a9d166b13b947b72f01fa/src/Integration/RequestIntegration.php#L169-L174

Ideally the `RequestIntegration` should compute the body size that would actually be sent to the Sentry servers or at least exclude the uploaded files total size from the body's size.

**Comment by Jean85** [comment]
This may seem an interesting suggestion at first, but I'm not sure that's doable, at least not in an easy and reliable way.

The size taken from the request metadata is the only fast and reliable way that we have to evaluate the situation while processing an event before sending it; any other approach is complicated and not general.
The body is 99% of the time a stream, so it doesn't have a simple `getSize()` on it, we would have to read it all, which could lead to memory exhaustion; or we could read it up to the size limit, which could lead to memory exhaustion again, or to the necessity of partial parsing, that could be hard if not impossible, since we're not sure about the content and its format.
