### ISSUE TITLE
versions on packagist are outdated

### ISSUE THREAD

**Issue by PJHRobles** [getsentry/sentry-php#1180]
I am updating several libraries for PHP 8 compatibility. Some libraries used on the current SDK we use are broken/deprecated. I am trying to update the sdk to 3.1.1, however, `composer update sentry/sdk` cannot see 3.1.1 which has PHP 8 support. Upon checking, it looks like the versions on packagist are outdated https://packagist.org/packages/sentry/sdk

How do you use Sentry?
 self-hosted/on-premise `20.7.0.dev0cc9f7d1`
Which SDK and version?
PHP 2.1.0
### Steps to Reproduce
1. Pin `sentry/sdk` to `^3.1.1`.
2. Run `composer upgrade sentry/sdk`

### Expected Result
Library gets upgraded

### Actual Result
```
  Problem 1
    - The requested package sentry/sdk ^3.1.1 exists as sentry/sdk[0.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.2.0, 3.0.0, 3.0.0-beta1, 3.1.0, dev-master] but these are rejected by your constraint.
```

**Comment by PJHRobles** [comment]
Another thing, although irrelevant to the issue, are there plans on releasing a 2.x version with PHP 8 support?

**Comment by Jean85** [comment]
2.x will not be updated as of now due to massive issues with the CI and the overlap with Xdebug 2/3 that does interfere with how errors are reported.

As for upgrading to PHP 8.0, you're requiring a package version that doesn't exist: `sentry/sdk` is a metapackage that lives in https://github.com/getsentry/sentry-php-sdk, which in turn requires this repo (which is listed as `sentry/sentry`). So, you need to require `sentry/sdk` to `^3.1` and run a Composer update with all sub-dependencies to get everything updated.

**Comment by PJHRobles** [comment]
Ahh right 🤦🏼 . Thanks for the explanation @Jean85!

**Comment by nickel715** [comment]
I had the same issue. After running `composer up --with-all-dependencies sentry/sdk` the sdk got upgraded to 3.1.3
