### ISSUE TITLE
Some exceptions are not reaching sentry.io (guzzle promise rejected)

### ISSUE THREAD

**Issue by fractalf** [getsentry/sentry-php#1187]
* PHP - 7.3.19
* Lumen - 8.2.1
* Sentry sdk - 3.1.0

I'm experiencing some exceptions of type `PDOException` and `ErrorException` not reaching sentry.io on actual exceptions.

If I test like this it works:

```php
throw new PDOException('PDOException test');
throw new ErrorException('ErrorException test');
```

..but not on actuall exceptions. This happened twice in production, I saw it in the logs. I was able to reproduce locally

I traced the error to this part of the SDK

`lumen/vendor/sentry/sentry/src/Client.php`

```php
    public function captureEvent(Event $event, ?EventHint $hint = null, ?Scope $scope = null): ?EventId
    {
        $event = $this->prepareEvent($event, $hint, $scope);

        if (null === $event) {
            return null;
        }

        try {
            /** @var Response $response */
            $response = $this->transport->send($event)->wait();
            $event = $response->getEvent();

            if (null !== $event) {
                return $event->getId();
            }
        } catch (\Throwable $exception) {
        }

        return null;
    }
```

The sending of the exceptions fails and I couldn't debug/understand why the promise is rejected

The exception in the catch here have this output (sorry for the long wall of text)

```
/code/lumen/vendor/sentry/sentry/src/Client.php:165:
class GuzzleHttp\Promise\RejectionException#3586 (9) {
  private $reason =>
  class Sentry\Response#3574 (2) {
    private $status =>
    class Sentry\ResponseStatus#3579 (1) {
      private $value =>
      string(6) "FAILED"
    }
    private $event =>
    class Sentry\Event#423 (28) {
      private $id =>
      class Sentry\EventId#2070 (1) {
        ...
      }
      private $timestamp =>
      double(1613680413.2212)
      private $startTimestamp =>
      NULL
      private $level =>
      class Sentry\Severity#3649 (1) {
        ...
      }
      private $logger =>
      string(3) "php"
      private $transaction =>
      NULL
      private $serverName =>
      string(12) "0dcbcacbf909"
      private $release =>
      NULL
      private $message =>
      NULL
      private $messageFormatted =>
      NULL
      private $messageParams =>
      array(0) {
        ...
      }
      private $environment =>
      string(5) "local"
      private $modules =>
      array(0) {
        ...
      }
      private $request =>
      array(0) {
        ...
      }
      private $tags =>
      array(1) {
        ...
      }
      private $osContext =>
      class Sentry\Context\OsContext#3613 (4) {
        ...
      }
      private $runtimeContext =>
      class Sentry\Context\RuntimeContext#3614 (2) {
        ...
      }
      private $user =>
      NULL
      private $contexts =>
      array(0) {
        ...
      }
      private $extra =>
      array(0) {
        ...
      }
      private $fingerprint =>
      array(0) {
        ...
      }
      private $breadcrumbs =>
      array(2) {
        ...
      }
      private $spans =>
      array(0) {
        ...
      }
      private $exceptions =>
      array(1) {
        ...
      }
      private $stacktrace =>
      NULL
      private $sdkIdentifier =>
      string(18) "sentry.php.laravel"
      private $sdkVersion =>
      string(5) "2.3.1"
      private $type =>
      class Sentry\EventType#3651 (1) {
        ...
      }
    }
  }
  protected $message =>
  string(24) "The promise was rejected"
  private $string =>
  string(0) ""
  protected $code =>
  int(0)
  protected $file =>
  string(53) "/code/lumen/vendor/guzzlehttp/promises/src/Create.php"
  protected $line =>
  int(62)
  private $trace =>
  array(8) {
    [0] =>
    array(6) {
      'file' =>
      string(62) "/code/lumen/vendor/guzzlehttp/promises/src/RejectedPromise.php"
      'line' =>
      int(64)
      'function' =>
      string(12) "exceptionFor"
      'class' =>
      string(25) "GuzzleHttp\Promise\Create"
      'type' =>
      string(2) "::"
      'args' =>
      array(1) {
        ...
      }
    }
    [1] =>
    array(6) {
      'file' =>
      string(47) "/code/lumen/vendor/sentry/sentry/src/Client.php"
      'line' =>
      int(158)
      'function' =>
      string(4) "wait"
      'class' =>
      string(34) "GuzzleHttp\Promise\RejectedPromise"
      'type' =>
      string(2) "->"
      'args' =>
      array(0) {
        ...
      }
    }
    [2] =>
    array(6) {
      'file' =>
      string(47) "/code/lumen/vendor/sentry/sentry/src/Client.php"
      'line' =>
      int(140)
      'function' =>
      string(12) "captureEvent"
      'class' =>
      string(13) "Sentry\Client"
      'type' =>
      string(2) "->"
      'args' =>
      array(3) {
        ...
      }
    }
    [3] =>
    array(6) {
      'file' =>
      string(50) "/code/lumen/vendor/sentry/sentry/src/State/Hub.php"
      'line' =>
      int(139)
      'function' =>
      string(16) "captureException"
      'class' =>
      string(13) "Sentry\Client"
      'type' =>
      string(2) "->"
      'args' =>
      array(2) {
        ...
      }
    }
    [4] =>
    array(6) {
      'file' =>
      string(38) "/code/lumen/app/Exceptions/Handler.php"
      'line' =>
      int(42)
      'function' =>
      string(16) "captureException"
      'class' =>
      string(16) "Sentry\State\Hub"
      'type' =>
      string(2) "->"
      'args' =>
      array(1) {
        ...
      }
    }
    [5] =>
    array(6) {
      'file' =>
      string(65) "/code/lumen/vendor/laravel/lumen-framework/src/Console/Kernel.php"
      'line' =>
      int(238)
      'function' =>
      string(6) "report"
      'class' =>
      string(22) "App\Exceptions\Handler"
      'type' =>
      string(2) "->"
      'args' =>
      array(1) {
        ...
      }
    }
    [6] =>
    array(6) {
      'file' =>
      string(65) "/code/lumen/vendor/laravel/lumen-framework/src/Console/Kernel.php"
      'line' =>
      int(118)
      'function' =>
      string(15) "reportException"
      'class' =>
      string(28) "Laravel\Lumen\Console\Kernel"
      'type' =>
      string(2) "->"
      'args' =>
      array(1) {
        ...
      }
    }
    [7] =>
    array(6) {
      'file' =>
      string(19) "/code/lumen/artisan"
      'line' =>
      int(35)
      'function' =>
      string(6) "handle"
      'class' =>
      string(28) "Laravel\Lumen\Console\Kernel"
      'type' =>
      string(2) "->"
      'args' =>
      array(2) {
        ...
      }
    }
  }
  private $previous =>
  NULL
  public $xdebug_message =>
  string(10587) "
GuzzleHttp\Promise\RejectionException: The promise was rejected in /code/lumen/vendor/guzzlehttp/promises/src/Create.php on line 62

Call Stack:
    0.0002     390800   1. {main}() /code/lumen/artisan:0
    0.1392    7980024   2. App\Console\Kernel->handle($input = class Symfony\Component\Console\Input\ArgvInput { private $tokens = [0 => 'nivel:test']; private $parsed = []; protected $definition = class Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 1"...
}
```

**Comment by ste93cry** [comment]
From the var_dump you posted I see that the response status is `failed` which gets set in two cases:

https://github.com/getsentry/sentry-php/blob/62f6897e1e577de39b366b5c84e19a453da36016/src/Transport/HttpTransport.php#L117
https://github.com/getsentry/sentry-php/blob/62f6897e1e577de39b366b5c84e19a453da36016/src/ResponseStatus.php#L101-L102

In both cases, it should be a fatal error on the server. Did you check if Sentry is returning a 500?

**Comment by fractalf** [comment]
Thanks for those pointers.

I dug deeper and found out it's the sentry server returning `413 Request Entity Too Large` ..

I see there are a couple of issues, also found out about the  `max_breadcrumbs` and `max_value_length` options, but neither seem to work.

How would you fix this properly?

**Comment by ste93cry** [comment]
>I can't trust exceptions being sent to sentry

It may very well be that I'm remembering wrong, but I think that a lot of time ago I read somewhere that Sentry is not trying to be a 100%-reliable tool to collect all errors that happen in the application. In fact, it works as an aggregator of data to give you a glampse of what's happening in the application, it's not a logger. But as I said, don't take my words as a fact.

>How would you fix this properly?

The `max_value_length` option should indeed trim the value, so if it's not happening then there may be a bug somewhere (the serializer is actually a mess because it's the only piece of code that we almost never touched/refactored since v1, albeit it's always a temptation for me). The other way to work around the issue may be using `before_send` option to customize the event before it's sent

>I get some kind of indication something is wrong

If you initialize the client using the [builder](https://github.com/getsentry/sentry-php/blob/51af981636bbe97fe9271dab76819d02593c3191/src/ClientBuilder.php), you can set a PSR-3 instance that will log some debug messages. Just ensure that this if you are using the Monolog handler this logger does not report back to Sentry or you will create a circular loop

**Comment by Jean85** [comment]
> The max_value_length option should indeed trim the value, so if it's not happening then there may be a bug somewhere (the serializer is actually a mess because it's the only piece of code that we almost never touched/refactored since v1, albeit it's always a temptation for me). The other way to work around the issue may be using before_send option to customize the event before it's sent

Maybe the limit is not working due to a stream? We can't reliably know how long a stream is, so we can't stop it in advance... Maybe we can do some trimming afterwards?

**Comment by ste93cry** [comment]
We're talking about how the event is serialized, no stream is involved here... I think that we simply don't apply the `max_value_length` to all properties of the event before serializing it to JSON

**Comment by fractalf** [comment]
Thanks guys for taking your time to discuss this.

**Comment by fractalf** [comment]
Thanks guys for taking your time to discuss this.

I would argue that the most important task of sentry is to **notify** when something wrong/unexpected happens, at least that's our use case. Most applications have server logs with details, so the stack trace is nice ofc, but not really as important as getting the message that something bad happened.

I'm sorry to say I cannot dig much deeper on this due to an overwhelming amount of work on my desk, but if you guys need me to do some simple debugging I'll do it.

@ste93cry I saw that other issue where a user used `before_send` to do his own normalizing. I tried it out, didn't work off the shelf, then just left it as my hack kind of fixes the main problem for me => notifying me

**Comment by PrinsFrank** [comment]
I just looked into this as well, as we had the suspicion some exceptions were never reported but we didn't have any reproductions before. In this case we had a ViewException with a long stacktrace and several big variables that didn't get reported, with the same 413 "Entity Too Large" response.

The Exception did get logged, but never came to our attention so was never fixed.

I've spent too much time on this for now so won't be able to find the underlying cause, but I did implement a workaround replacing
```
app('sentry')->captureException($e);
```
With
```
$reportedException = app('sentry')->captureException($e);
if ($reportedException === null) {
    app('sentry')->captureException(new UnreportableException($e->getMessage, $e->getCode(), $e->getPrevious));
}
```

It's not pretty but it works. Hopefully I will have some time soon to find the underlying cause.

**Comment by ste93cry** [comment]
I'm not sure how we can solve the issue here... Any solution we take could be a good choice for someone and a bad one for someone else, as it's too dependant on the context of the application that is running the SDK. From a server-side perspective instead, I don't know if it's possible to set an higher limit for the data

**Comment by PrinsFrank** [comment]
If we can get an authoritive answer on what the maximum report size is (I am finding different historical numbers on the sentry forum) we could keep track of the size of stacktraces and other info and discard any info that exceeds that threshold. That seems like a lot of work however, especially since there are a lot of variables that can be set. I am actually very happy with the solution above, as even though almost all info was stripped it still helped us to locate a persistent issue, so maybe just reporting a stripped down exception on 413 response is an okayish solution for now?

**Comment by stayallive** [comment]
We can find a partial answer here: https://develop.sentry.dev/sdk/event-payloads/.

> Event payload size limit is 200kb.

However, I believe that is not translated to the actual maximum allowed request body size and probably changes from time to time. It's not really a Sentry server limit but it is I believe forced on the webserver side, so the max request body size depends on the NGINX config or whatever and for self-hosted can probably be adjusted as needed.

I also can't find an max request body size answer anywhere but maybe someone from @getsentry/client-infra is able to provide an answer to the question what the max request body size is for events sent to sentry.io.

---

There are a few things we could do like stripping data from the event until we are able to sent (like the request body and/or breadcrumbs), maybe we can even communicatie in the event we stripped some data because it was limited by the server but not sure what the correct or expected way is here.

**Comment by HazAT** [comment]
https://develop.sentry.dev/sdk/envelopes/#size-limits

Did you disable gzip compression? (with `enable_compression`)
I don't have a good solution for this now, it seems like the message you are trying to set that contains the query is just too long.

**Comment by WalrusSoup** [comment]
For anyone who stumbles across this topic where sentry is not gettin **_any_** exceptions:

We have some worker servers in our fleet that never turn off. It turns out that we were missing an update for our ca-certificates with openssl and as a result, sentry was returning all the right things and getting an event ID but underneath it was failing the SSL handshake. I suggest you run `curl -v https://o29515.ingest.sentry.io` to see if it applies to you and follow the instructions [here](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-expired-certificate/) until you can get the next platform upgrade.
