### ISSUE TITLE
Indicate when message is not processed by the monolog handler, to disable bubbling

### ISSUE THREAD

**Issue by EvgeniiR** [getsentry/sentry-php#1189]
Hello!
[Monolog\Handler\HandlerInterface::handle](https://github.com/Seldaek/monolog/blob/c1971982c3b792e488726468046b1ef977934c6a/src/Monolog/Handler/HandlerInterface.php#L47-L50) allows returning false to indicate that message is not handled for some reason, so it'll be passed to next registered monolog handlers, even when ```$bubble == true```.

I think it would be great for sentry monolog handler to overwrite this method to return false when some error happened during processing

**Comment by ste93cry** [comment]
By default, the `$bubble` argument of the constructor is set to true. This means that since the [base implementation class](https://github.com/Seldaek/monolog/blob/c1971982c3b792e488726468046b1ef977934c6a/src/Monolog/Handler/AbstractProcessingHandler.php#L44) does `false === $this->bubble`, it should return `false` every time. Are you using the handler with `$bubble = false` instead?

**Comment by EvgeniiR** [comment]
@ste93cry I'm using $bubble = false to prevent future processing after event is sent to Sentry, but sometimes my on-premise instance of Sentry may be unavailable, so I want to fallback to another error monitoring system

**Comment by ste93cry** [comment]
Wouldn't changing the current behavior go against the purpose of the `$bubble` argument?

>Whether the messages that are handled can bubble up the stack or not

https://github.com/Seldaek/monolog/blob/c1971982c3b792e488726468046b1ef977934c6a/src/Monolog/Handler/AbstractHandler.php#L29

>true means that this handler allows bubbling. false means that bubbling is not permitted.

https://github.com/Seldaek/monolog/blob/c1971982c3b792e488726468046b1ef977934c6a/src/Monolog/Handler/AbstractHandler.php#L71

Basically, you're saying that in case an error occurs while sending the event, you would like the message to be handled by other handlers, regardless of whether this is permitted or not according to `$bubble`. Am I right?

**Comment by EvgeniiR** [comment]
> Basically, you're saying that in case an error occurs while sending the event, you would like the message to be handled by other handlers, regardless of whether this is permitted or not according to $bubble. Am I right?

Yep!

> Whether the messages that are handled can bubble up the stack or not

I'm considering message as "not handled" when error occurred while sending.

**Comment by ste93cry** [comment]
>I'm considering message as "not handled" when error occurred while sending.

The second statement though is more general in the wording instead, therefore open to a possible different interpretation. I had a look at the built-in handlers of Monolog and they all avoid bubbling if `$bubble = false`, therefore our handler is in effect respecting the general expected behaviour. Plus, we're implementing the `write()` method whose return type is `void`, definitely preventing any way to return something to the caller (`handle()`) and consequently reinforcing my idea that either this is done by-design or that it is wrong. I definitely see the usefulness of the request, but I suggest to open an issue in the Monolog repo to understand what is the general expectation before making any change here and diverging the behaviour from all the other handlers
