### ISSUE TITLE
Sentry performance empty (no performance is gauged)

### ISSUE THREAD

**Issue by haroonahmed0044** [getsentry/sentry-php#1197]
Hi Everyone,
I have configured sentry, install all the required configurations related to the sentry.
I'm using php for the my application, and used sentry-php configurations, but not getting any data in the performance tab.
Even though i have exhausted all 10,000 events at first.

Please support in this regard.

Thanks

**Comment by stayallive** [comment]
Hi @haroonahmed0044, are you using just the plain PHP SDK (no framework integration like Symfony or Laravel)?

Because if that's the case there is no automatics instrumentation available and you will need to add your own to get data sent to Sentry: https://docs.sentry.io/platforms/php/performance/#custom-instrumentation.

**Comment by ste93cry** [comment]
I'm closing this because a lot of time passed without any answer. Feel free to reopen should you need more help
