### ISSUE TITLE
Add Documentation Surrounding How to sanitize/process requests for sensitive data

### ISSUE THREAD

**Issue by cwlowder** [getsentry/sentry-php#1230]
# Problem
The old raven library had processors you could add to your configuration to sanitize your HTTP requests such as `Raven_Processor_SanitizeDataProcessor`. These Processors were removed in the upgrade to 2.0.0: https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md. I want to be able to replicate this behavior in the newest version of the library. However, I can't find much on how to do that in either this repository or the official documentation. The closest I could find is this thread in the python version of the library: https://github.com/getsentry/sentry-python/issues/211, which references using before_send. The php version of the library has this same function, however, there isn't a good example of using it as far as I can see.
# What I want
I would love to have a simple code snippet demonstrating how to sanitize an http request for different headers/cookies that may contain API keys and other sensitive information.
Something like how to accomplish this from the old library:
```
'processorOptions' => array(
    'Raven_Processor_SanitizeDataProcessor' => array(
                'fields_re' => '/(user_password|user_token|user_secret)/i',
                'values_re' => '/^(?:\d[ -]*?){15,16}$/'
            )
)
```
Thanks for your time!

**Comment by ste93cry** [comment]
First of all, I strongly suggest you to investigate [Relay](https://docs.sentry.io/product/relay/) which was born for the exact purpose of sanitizing data from events before sending it to the server. Yes, it's another piece of infrastructure to maintain, but it has a lot of built-in features like regex matches and so on so that you don't have to code themselves in your applications. If you still want to stick with using the plain SDK, the `before_send` callback is for sure one way to go, but be aware that it works only for events and not transactions (if you're using the Tracing feature)

```php
\Sentry\init([
    'before_send' => static function (Event $event): Event {
        $request = $event->getRequest();

        // Apply logic here to sanitize the request data. Payload details can be found at https://develop.sentry.dev/sdk/event-payloads/request/#attributes

        $event->setRequest($request);

        return $event;
    }
]);
```

There is even an easier solution if you set `send_default_pii = false`: by configuring the [`RequestIntegration`](https://github.com/getsentry/sentry-php/blob/3d733139a3ba2d1d3a8011580e3acf0ba1d0dc9b/src/Integration/RequestIntegration.php) you can customize which headers you want to be filtered, but it doesn't work for cookies and the feature simply matches a list of header names against the ones that you configured, so there are no fancy stuffs like matching against a regex or whatever else

**Comment by Jean85** [comment]
Check also for server-side options too: https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/

**Comment by ste93cry** [comment]
I’m closing this because I think the answer is enough explanatory. Feel free to reopen should you still have issues
