### ISSUE TITLE
Project IDs should be strings

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-php#1292]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)

Which SDK and version?
PHP

### Steps to Reproduce

https://github.com/getsentry/sentry-php/blob/ea704bbe145657a507d73cd8bf6cc017d269fffa/src/Dsn.php#L102

### Expected Result

Project IDs should be cast as strings, not int

### Actual Result

Project IDs are int in from PHP sdks

we need project ID to not be forced to an integer because its plausible we will need it to be a UUID, or we will need it to be a 64 bit int (which breaks in JS, as an example)

**Comment by Jean85** [comment]
This has repercussions on sentry-laravel and sentry-symfony too for sure.

**Comment by stayallive** [comment]
@Jean85 repercussions in what way? Does the Symfony integration use the project IDs directly? I just don't see how removing the cast and making sure it can be a string changes anything but I might be missing something...?

**Comment by Jean85** [comment]
Mh no you're right, I thought we input those manually, but it's not like that, it comes from the DSN so it's transparent there.

**Comment by ste93cry** [comment]
Beware that we cannot simply change the typehint from `int` to `string` because that would be a breaking change. The best we can do it to remove it entirely and add an optional argument to the getter to decide whether to return the old value or the new one. Then in the next major version all these workarounds can be safely removed

**Comment by stayallive** [comment]
@smeubank I suppose this is more of a future proofing thing? Or is there an actual (short-ish) term timeline this needs be working? 

Otherwise it's probably fine to move this change to a new major version exclusively, we have a few other things also up for removal/adding but a major release will probably be a few weeks out yet.

**Comment by smeubank** [comment]
sorry for the late reply @stayallive this is future proofing but also we'd like it fixed rather soon just to ensure we don't build up any more bad IDs

is there any rough timeline for the next major release of sentry-php?

**Comment by ste93cry** [comment]
There's no need for a major version, as soon as the mentioned PR gets merged I will release the fix. The major version is needed to remove some workarounds needed here and there to support switching a getter method from int to string, but there's no need to rush the cleanup 😃
