### ISSUE TITLE
guzzlehttp/psr7 dependency has know vulnerabilities

### ISSUE THREAD

**Issue by lmeyer** [getsentry/sentry-php#1300]
Hello,

I put this bug report here even if I run symfony bundle has the bug is not bundle related.

Regards

### Environment

- Sentry SaaS (sentry.io)
- php8.0.2
- Symfony 6.0.3
- sentry/sentry-symfony 4.2.8

Which SDK and version?
- PHP sentry/sentry 3.3.7

### Steps to Reproduce

1. Ran `bin/symfony check:security`

### Expected Result

```
$ bin/symfony check:security

Symfony Security Check Report
=============================

No packages have known vulnerabilities.
```

### Actual Result

```
$ bin/symfony check:security

Symfony Security Check Report
=============================

1 package has known vulnerabilities.

guzzlehttp/psr7 (2.1.0)
-----------------------

 * [CVE-2022-24775][]: Inproper parsing of HTTP headers

[CVE-2022-24775]: https://github.com/guzzle/psr7/security/advisories/GHSA-q7rv-6hp3-vh96

$ composer why guzzlehttp/psr7

sentry/sentry                     3.3.7  requires  guzzlehttp/psr7 (^1.7|^2.0)
```

**Comment by ste93cry** [comment]
Thanks for reporting this. Would you mind opening a PR that updates the constraint in the `composer.json` file?

**Comment by Jean85** [comment]
Are we sure that we want bump this? I was always on the impression that it's not the job of other packages to restrict dependencies only due to vulnerabilities. In fact, the code would still work, it's the end user's job to check for those kind of stuff.

Otherwise I would simply require `roave/security-advisories` and call it a day.

**Comment by lmeyer** [comment]
Hi @Jean85 

I really don't know what's the best option in fact :
- Update the `composer.lock` in my project and tell the package nothing
- Report the security issue to the package

**Comment by Jean85** [comment]
> I don't see any issue in asking a more recent version if that's for security reasons, do you?
We may force downstream users to upgrade, even if the vulnerability is de-facto not applicable to our case. I would try to avoid doing this in a patch release, at the very least.

If we want to follow this approach, we could use Dependabot to do it.

**Comment by stayallive** [comment]
I don't want to create a messy dependabot mess here if we can prevent it.

Fine to bump the contstraints in the `composer.json` since it's very low effort but honestly I don't really see the need since a `composer update` on the user side also "fixes" it by updating to the latest version since our constraints allow that. No need to police the dependencies there are better tools for that but again I'm fine with bumping our constraint to only include "safe" versions if we feel better about that but please no dependabot here since that makes no sense unless in the case where our constraints dissallow upgrading to a safe version but I don't think we have strict enough constraints for that to likely happen.

**Comment by ste93cry** [comment]
Agree on Dependabot, I don't think there's the need for a lib project to have it enabled, even more if we have to follow semver and we cannot bump dependencies at willing

>I would try to avoid doing this in a patch release, at the very least

When security is impacted, there's no patch or minor release that you have to think of, you just do what is needed to close the hole

> No need to police the dependencies there are better tools for that

I'm not a security expert, so I don't know what the best practices are in cases like this. However, I strongly believe that it makes sense to require a non-vulnerable version of a dependency we ourselves rely on, because the same bug today affects our end users and tomorrow may affect our very own code

**Comment by Jean85** [comment]
> I don't think there's the need in a lib project to have it enabled for keeping all dependencies updated indiscriminately. However, I think that receiving the notice that we're using a vulnerable dependency is something that we might want to reason on

That's what I was suggesting: if we want to reason about security issues, enabling Dependabot for them only should be the way to go. But that IMHO is a policy that should be implemented and the org level, and if they didn't do it yet, I doubt it will be done. @HazAT can you lean on the topic here?

> When security is impacted, there's no patch or minor release that you have to think of, you just do what is needed to close the hole

That reasoning is sensible when the security issue is in your code, or you're an end user project. When the vuln is an indirect dependency, I'm not sure we should make that call, because you cannot do a blanket statement where every vuln is impacting.

**Comment by ste93cry** [comment]
>When the vuln is an indirect dependency

I think that's the key here. It's a direct dependency for us, so we're susceptible to the same security issues as would be the final user, in this case.
