### ISSUE TITLE
SDK performance negatively affects application if Sentry is offline.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-php#1311]
This came up on Twitter: https://twitter.com/JasnK/status/1522640769089249281

> Sentry PHP SDK 3.1.1 and the latest Sentry DSN shown in Client Keys.

Related issues: https://github.com/getsentry/mobile-team-meta/issues/3

**Comment by mfb** [comment]
Being able to set the Symfony HTTP client max_duration and timeout options would help here - see PR at #1282

e.g. if there is no connection after _n_ seconds, the HTTP client's timeout would be reached and send could be aborted.

**Comment by jason-klein** [comment]
Thank you Bruno! We are using Sentry PHP SDK 3.1.1 with Laravel 9.10.1 and PHP 8.0.18 on Apache 2.4.51 in a Docker Container hosted on AWS ECS/EC2.

We are using the latest Sentry DSN shown in Client Keys.  Our DSN is formatted like the following example:
`https://1234567890abcdef1234567890abcdef@o9999999.ingest.sentry.io/9999999`

**Summary**
The Sentry SDK had a negative impact on our web-based application performance. Our average page load times increased 30X-90X from 275-280 ms up to 8-25 seconds during the Sentry outage that began around 2022-05-06 10:00 UTC. When we realized Sentry was the issue and re-deployed our services with the Sentry SDK disabled, the problem immediately disappeared.

**Diagnosing Issue**
- External monitoring and our web load balancer both confirmed that TTFB (time to first byte) on our application servers had increased nearly 100x.
- Web traffic was normal. No unusual spikes in web requests or HTTP error codes.
- Server metrics were normal. (e.g. Database/Cache/Container CPU/Memory/Disk, etc)
- **Sentry** indicated that our PHP application response times were normal
- Cross-referencing the original request time in Apache logs with the HTTP response header time and TTFB in browser inspection confirmed that Apache was receiving the request immediately, but responding slowly.

The information above led us to believe there was a problem with a network-based service that our application depends on to process each request (e.g. DNS). We eventually determined Sentry was causing our issues, by keeping PHP requests running much longer than usual which depleted all available PHP workers across all of our Apache container instances. When a PHP request would finally timeout, that worker became available to service another request.

**Temporary Solution**
Disable Sentry SDK during Sentry outage

**Attempted Solutions**
Twitter/Zeeg suggested that an [outdated Sentry DSN could cause an issue](https://twitter.com/zeeg/status/1522593601598869504), so we immediately confirmed we were using a current DSN.

We reduced SDK setting `send_attempts` from 3 attempts (default) to 1 attempt while the Sentry outage was still ongoing. This may have reduced average page load times, but it did not resolve the issue.

We explored the possibility of reducing the SDK HTTP client connect/request timeouts, but the timeouts are hard-coded in [HttpClient](https://github.com/getsentry/sentry-php/blob/64b9696d965994e0bdbd35da8e6de90bc39a269f/src/HttpClient/HttpClientFactory.php#L37).

@bruno-garcia Suggested the Sentry SDK [should gracefully downgrade](https://twitter.com/brungarc/status/1522639084820250627) and he opened this issue.

**Comment by mfb** [comment]
In my experience, send_attempts should actually be 0 - as this defines the resend attempts, not send attempts. If my app failed to send an error to Sentry, I don't want to wait another X seconds to try to send it again.

**Comment by jason-klein** [comment]
@mfb Thank you for the confirmation! I agree. We are not worried about an occasional lost event since we are not needing to record 100% of events. I assume most clients are only going to have Sentry sample a small % of their events, so losing an occasional event should not be a problem.

PHP SDK Documentation for [Configuration Options](https://docs.sentry.io/platforms/php/configuration/options/) says:

> send_attempts
> Controls how many times the SDK will attempt to resend an event to Sentry. The default is 3.

Because the option name was inconsistent with the option description (e.g. "send" vs "resend"), we tried to confirm if `send_attempts` value of `0` meant no **attempts** or no **re-attempts** in [HttpClient](https://github.com/getsentry/sentry-php/blob/64b9696d965994e0bdbd35da8e6de90bc39a269f/src/HttpClient/HttpClientFactory.php#L107). We ended up going with the value of `1` to be safe.

We will configure `send_attempts` with a value of `0`. Assuming this does not impact our event reporting to Sentry, I will submit a PR to the docs as follows:

> send_attempts
> Controls how many times the SDK will attempt to resend an event to Sentry.  The default is 3, which means the SDK will attempt to resend an event up to 3 times after the initial attempt for a total of 4 attempts. Setting this value to 0 will disable attempts to resend an event, but will not disable the original attempt to send the event.

**Any idea where we can find the source for the [Configuration Options ](https://docs.sentry.io/platforms/php/configuration/options/) page?** Unable to find this content in the [Sentry Docs repo](https://github.com/getsentry/sentry-docs/tree/master/src/platforms/php).

**Comment by stayallive** [comment]
There is a link on the bottom of that page that links directly to the source of that page!

It here: https://github.com/getsentry/sentry-docs/edit/master/src/platforms/common/configuration/options.mdx

**Comment by Jean85** [comment]
I was hit by a similar issue due to the same Sentry server-side incident. #1282 would definitely reduce the impact of this, we need to push that further.

**Comment by smeubank** [comment]
have this on the agenda for our technical steering committee this week

**Comment by smeubank** [comment]
After some discussion and the mentioned issue https://github.com/getsentry/sentry-php/pull/1282 My suggestion is to agree with the above `send_attempts` default to 0, and we just need to agree if we can do this in a minor bump

**Comment by ste93cry** [comment]
Technically speaking, we can't. People know that since version `3.0` the default value for the option is 3, and if we change it without bumping the major version we will break people's expectations, without them even noticing it. However, bumping the major version just for this seems a little weird. Given that here and there we have deprecated things to clean up and missing features to implement, my suggestion is to write down a list of things that we want for the next major (comprising this one) and start working on it

**Comment by mfb** [comment]
I've seen defaults change in patch-level versions of libraries if it could be classified as a bug or security vulnerability and is well documented.

Granted some of those libraries don't have the best reputation, e.g. OpenSSL, but it was bugs that caused that, not the fixes :)

In this case, seems reasonable to classify as broken behavior that should be fixed, with clear documentation about the change and how to reconfigure it.

**Comment by ste93cry** [comment]
If we want to treat the default value as wrong since the beginning (and to be honest I think that this option should have never been existed) then I could also approve. In any case, although I tend to agree that most of the people probably didn't even bothered looking at what this option does, they expect that if the default is 3 then an event is sent up to 3 times before giving up. If we change this behaviour without communicating it, we're open to complaints because suddenly people will see a different behaviour and will not understand why. That's why semversioning exists, which we're deliberately breaking it now, because we're not fixing a bug, technically speaking. We can make this choice consciously of course, and we should for sure add a note for it in the CHANGELOG, but it's not how things usually works in the PHP community where no breaking changes between minor/patches is a big expectation.

**Comment by HazAT** [comment]
Let's make it `0` in a minor & document it properly.
We can also deprecate the option and remove it in the next major.

**Comment by ste93cry** [comment]
We have an agreement. I will take care of opening the PR in the next days, if someone else doesn't do it beforehand
