### ISSUE TITLE
Scope::getTransaction returns null when Transaction isn't sampled

### ISSUE THREAD

**Issue by blackwolf12333** [getsentry/sentry-php#1333]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
sentry-php@3.4.0

### Steps to Reproduce

1. initialize sentry with a very low sample rate for easier repro
2. call `$transaction = startTransaction`
3. call `SentrySdk::getCurrentHub()->setSpan($transaction)`
4. call `SentrySdk::getCurrentHub()->getTransaction()`

### Expected Result

I expected to get the instance of the Transaction I just started.

### Actual Result

`getTransaction` returned null because when you call `startTransaction` and this transaction isn't getting sampled it does not initialize the SpanRecorder (Hub.php:256). However, `getTransaction` gets the transaction from `Scope` which checks for an active SpanRecorder and returns null otherwise.

This behavior is not documented anywhere, I think it would suffice to add a note to the `Hub::getTransaction` method that if it's not sampled it will return null.

**Comment by ste93cry** [comment]
I checked the code of the JS SDK (the code of this package is mainly a porting from it) and it looks like the same problem you are describing was also present there and it was considered a bug which got fixed in getsentry/sentry-javascript@5ac0fcadc57147cc8ec9517a43712796e8d2e621. I will try to open a PR soon to fix it here too
