### ISSUE TITLE
Introduce `includeLocalVariables` option

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-php#1448]
### Problem Statement

As per https://github.com/getsentry/develop/pull/813, add a `includeLocalVariables` option that controls if local variables should be included in the stackframes of exception events that gets sent to Sentry.

Note: this should only influence the data that is sent to Sentry, not the actual stacktraces of PHP exceptions.

### Solution Brainstorm

Update sentry options.

**Comment by stayallive** [comment]
We do have to be careful to link to [here](https://docs.sentry.io/platforms/php/troubleshooting/#missing-variables-in-stack-traces) when we document that feature for PHP, otherwise we will get even more confused support questions about it than we already do 😅

**Comment by AbhiPrasad** [comment]
It should be true by default.

**Comment by cleptric** [comment]
I'm not in favor of adding this option to the PHP SDK.

The presence of exception args is tightly coupled to the `zend.exception_ignore_args` ini directive.
By default, this directive is set to `On`, which already caused a lot of confusion from people using Sentry in the past.

I also don't see the use-case that someone would set `zend.exception_ignore_args: Off` and then disable `includeLocalVariables`.
If in the unlikely case, someone really needs to do that, they can utilize the `ini_set()` PHP function.

**Comment by mfb** [comment]
In the drupal integration we do have this setting (with a different name of course). This is because it controls what data is sent to Sentry (i.e. sent externally) vs what data is simply available internally to the application or other loggers. If our sentry send args setting is disabled but exception stack frames do contain the args due to the php ini setting, then we loop thru and remove them.  For the opposite case, we document that users need to both enable this setting and disable php's ignore_args ini setting.  For PHP errors and non-exception application error or debug events, we generate the stack frames ourselves by calling debug_backtrace() and use our sentry send args setting to determine if we call it with DEBUG_BACKTRACE_IGNORE_ARGS (no args) or 0 (with args but no object).

**Comment by cleptric** [comment]
Closing, for now, people can control the behavior via `zend.exception_ignore_args`
