### ISSUE TITLE
Add enableTracing option

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-php#1457]
A new simplified options for configuring to turn tracing & performance on should be added to all SDKs. For each SDK the default sample rate should be agreed upon.  

Docs do not need to be updated yet, nor the onboarding wizard. This can wait until the top level options are added to a number of SDKs and we decide if we want to configure the default onboarding experience, for all new users.

See [develop docs](https://develop.sentry.dev/sdk/performance/#enabletracing) for more information. This is a non-breaking change to be clear. Any of the three options should enable performance, alone or in combination

### Open point:
recommend default it 1.0 or 100%. Can discuss if it should be less.

**Comment by cleptric** [comment]
Holding off on this for the moment, as we cannot set a default `traces_sample_rate: 1.0` due to overhead concerns. I also don't have a good answer when it comes to a lower default value, as this heavily depends on the application and other factors like using a local Relay.

**Comment by stayallive** [comment]
Tracing is still opt-in right? 

So won't this extra option make no difference at all from what it is now (because it defaults to `false`? I mean if we tell users to set `traces_sample_rate: 1.0` or `enable_tracing: true` to enable tracing makes no difference for the end-result (and the implicated perf issues related to PHP) and the same warnings (using relay etc.) apply for both "methods". 

It's just a little nicer to tell users to `enable_tracing: true`, little syntax sugar if I'm reading it correctly?

**Comment by cleptric** [comment]
Yes, correct. I'm just afraid of hiding `traces_sample_rate: 1.0` as the default behind `enable_tracing: true`. If these concerns are not justified or too far-fetched, we can of course add the new option.
