### ISSUE TITLE
Composer Update Did Not Install Dependancies

### ISSUE THREAD

**Issue by dhky** [getsentry/sentry-php#1475]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.0.3

### Steps to Reproduce

One of our deployment pipelines initiated a `composer update`. That is usually fine. However, the `php-http/discovery' dependency was nit installed. That caused HTTP 500 errors. 

To resolve this, we added this decency directly to our `composer.json file`.

### Expected Result

The expected result would have been the `php-http/discovery` being installed.

### Actual Result

The package was not installed. This caused HTTP 500 errors.

**Comment by cleptric** [comment]
Thanks for reporting this issue.

Are there any blockers for you to use `v3` of the SDK? The last release of `v2´ was over two years ago, and I'm a bit reluctant to push any more updates for this major version.

There were some changes in `php-http/discovery` recently, maybe take a look at https://github.com/php-http/discovery/issues/213 to see if some of the comments might be helpful.
I assume you only need to allow the newly added plugin in your composer.json.

**Comment by Jean85** [comment]
I don't think this should be considered a bug. Running a `composer update` in an unattended way and expecting it to work every time is something out of scope for us, and I also don't think it's an expected feature from Composer itself. 

Lastly, that didn't probably work because plugins are disabled by default until enabled; https://github.com/composer/composer/pull/11315 may be related.

**Comment by cleptric** [comment]
Closing, as we do not have any plans to update the v2 branch.
