### ISSUE TITLE
Replace php-http/message-factory

### ISSUE THREAD

**Issue by mrsombre** [getsentry/sentry-php#1541]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.19.0

### Steps to Reproduce

Execute `composer require sentry/sentry`.

### Expected Result

I expect `psr/http-factory` is used and no warning appears.

### Actual Result

```
./composer.json has been updated
Running composer update sentry/sentry
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
59 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
Using version ^3.19 for sentry/sentry
```

**Comment by cleptric** [comment]
We currently rely on `php-http/message-factory` and can't easily remove this dependency without a likely breaking change. Closing as won't fix.

**Comment by nicogominet** [comment]
> Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
I also would like to get this fixed.

It looks like this is [a temporary solution](https://github.com/getsentry/sentry-php/pull/1534) anyway as @stayallive said, so I don't understand why the "won't fix" end-of-discussion answer here. Unless I misunderstood the other PR, if anything this **will** be fix "soon".

**Comment by cleptric** [comment]
For some more contex:

The Symonfy HTTP Client version 6.2 and below will throw an exception if `php-http/message-factory` is absent. See https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpClient/HttplugClient.php#L48-L50

While this behaviour was removed in 6.3 and up, we can't force people to upgrade to the latest version via the SDK. We already ran into this issue in https://github.com/getsentry/sentry-php/issues/1533, which was caused by `php-http/client-common` removing this dependency.

**Comment by nicogominet** [comment]
Thank you @cleptric for the explanation, I think I understand why this is happening now.

In my case, I believe this will be fixed when `6.3` will be released (currently latest is `RC2`).

**Comment by rintdev** [comment]
Hmm, can't we keep this issue open to track this? I'm trying to avoid using abandoned package dependencies.

**Comment by gndk** [comment]
> While this behaviour was removed in 6.3 and up, we can't force people to upgrade to the latest version via the SDK.

You are not forcing anybody to do anything. People using outdated Symfony versions are free to also keep using older sentry versions that still rely on the abandoned package.

**Comment by cleptric** [comment]
We currently support Symfony HTTP client version 4, 5 and 6. https://github.com/getsentry/sentry-php-sdk/blob/master/composer.json#L25

As I already explained, we cannot enforce the version of the Symfony HTTP client people use, hence versions [4](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpClient/HttplugClient.php#L49), [5](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/HttpClient/HttplugClient.php#L50) and all versions prior [6.3](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpClient/HttplugClient.php#L49) will throw an exception during runtime if we remove `php-http/message-factory`.

https://github.com/php-http/message-factory Contains five interfaces and ships no actual code. This is a compromise I'm willing to accept for the time being.

I'm happy to review a PR if anyone has a better idea.

**Comment by gndk** [comment]
People can just require `php-http/message-factory` on their own if they require it. Problem solved, no more exception during runtime after you remove it from sentry.

**Comment by devicenull** [comment]
Our security/compliance department is unhappy with us for having an abandoned package as a dependency.

**Comment by cleptric** [comment]
We might cut a new major version in the coming weeks that would resolve this. Big emphasis on _might_, as there are a few constraints that would come with this.

**Comment by binaryfire** [comment]
> Our security/compliance department is unhappy with us for having an abandoned package as a dependency.

Same. Unfortunately we've been forced to remove Sentry because of this.

**Comment by ste93cry** [comment]
Honestly, I can't understand why a security/compliance department would be so interested in complaining about the deprecation of a package that contains only interfaces and no code to maintain. Anyway, I also don't understand why we can't remove this dependency: from what I've read (I haven't followed the discussion much in the past), the problem was the initialization of the Symfony HTTP client which required the above package to be installed . The best solution in that case was to handle the initialization gracefully, not add a package that we're not even using directly (unless I'm blind)

**Comment by binaryfire** [comment]
@ste93cry Most security scanning is automated nowadays. Personally I think this should be taken care of by the package that's using the deprecated dependency, rather than asking consumers of the package to add exceptions to their security pipelines. Just my opinion though.

**Comment by ste93cry** [comment]
Removing a package just because it depends on a set of deprecated interfaces seems a bit exaggerated, but in general I agree with your thoughts, no doubts at all. Since we're not using those interfaces, unless I missed some references in the code, I don't understand @cleptric's choice of forcing the installation of that package instead of just handling the HTTP client initialization using a `try/catch` statement.

**Comment by abhibeckert** [comment]
> Honestly, I can't understand why a security/compliance department would be so interested in complaining about the deprecation of a package that contains only interfaces and no code to maintain.

The package have any problems right now... but it's no-longer maintained and if a problem is found in the future the lack of maintenance means nobody is going to fix it.

As to the issue in this specific case... I agree, there's not much real threat. But I'm not willing to make an exception and every time we run through continuous integration/deployment the issue of an unmaintained package pops up as a potential problem and my team wastes time investigating to check if it's a problem or not.

That's the real problem here - the wasted time caused by Sentry having an unmaintained dependency. And here I am, commenting on this issue, when I should be doing productive work. And everyone watching this will read my comment. More wasted time.

While it's a minor issue it's also one that affects literally everyone who uses PHP and Sentry, so it should be fixed sooner rather than later. It's now been over two months already. And the deprecation warning has crossed my radar hundreds of times (more than once a day).

If I wasn't so busy, I would have already forked `sentry-php`. But I'm really hoping I don't need to do that...

**Comment by cleptric** [comment]
We'll kick off working on the new major this week, so an update that solves the mentioned issue will be not too far out.

**Comment by ste93cry** [comment]
>I'm not willing to make an exception

If the `php-http/message-factory` repository had not been archived, you would have never known that those `interfaces` were not maintained anymore. World is full of compromises, it's up to you to discern which makes sense to accept and which not.

>If I wasn't so busy, I would have already forked `sentry-php`. But I'm really hoping I don't need to do that...

I would like to remind you that open source software lives on the contribution of people willing to dedicate their time to help develop it. While it is true that this package is backed by a company and there is a legitimate expectation that it will be maintained over time, this SDK has been developed primarily by open source contributors, so if you are concerned about this particular issue you can always step up and contribute to improve the situation.

>We'll kick off working on the new major this week, so an update that solves the mentioned issue will be not too far out.

This still doesn't explain why you decided to add the package to the `composer.json` instead of just wrapping the client initialization in a `try`/`catch` block. I have nothing against releasing a new major version, but I'm failing hard to see why it's needed.

_Note: I'm not affiliated with Sentry in any way, I'm just a contributor of this package with his own personal opinion_

**Comment by cleptric** [comment]
I explained this in https://github.com/getsentry/sentry-php/issues/1541#issuecomment-1568068745. Swallowing the exception doesn't help much, as in this case, no events will not be sent to Sentry, which is hard to surface to users.

**Comment by ste93cry** [comment]
How can swallowing the exception not help? The next HTTP client will be tried, so I don't see a particular issue with this. If neither of the clients can be instantiated, there is nothing Sentry can do...

**Comment by cleptric** [comment]
Requiring the package directly was done to solve issues like https://github.com/getsentry/sentry-php/issues/1533 and https://github.com/getsentry/sentry-laravel/issues/694.
We opted to rather not crash users' applications.

**Comment by ste93cry** [comment]
Wouldn't a `try`/`catch` around the initialization of the Symfony HTTP client just catch the error and let the factory try the other HTTP clients?

```diff
+try {
    if (class_exists(SymfonyHttplugClient::class)) {
        ...
        
        return new SymfonyHttplugClient(SymfonyHttpClient::create($symfonyConfig));
    }
+} catch (Throwable $exception) {
+    // Do nothing on purpose, so that the next HTTP client can be tried
+}
```

**Comment by cleptric** [comment]
Using `sentry/sentry-sdk` and catching the raised exception will result in the same `LogicException` exception being thrown, as `HttpAsyncClientDiscovery` will resolve to `SymfonyHttplugClient` yet again.

**Comment by ste93cry** [comment]
You're right, if we assume that the user has no other HTTP client installed besides `symfony/http-client`. But is this enough to justify your choice of forcing an obsolete package for everyone else? I also wonder why `php-http/message-factory` isn't required in `sentry/sentry-sdk`. I realize this just moves the issue from one place to another, but at least the core SDK which does not depends at all from those interfaces remains clean.

**Comment by cleptric** [comment]
I did consider using an abandoned package less severe than causing an exception.

**Comment by ste93cry** [comment]
Considering the amount of people complaining here and "+1" the first comment, maybe this decision should be reconsidered. What about my suggestion of moving the requirement of the abandoned package to the meta-package? If someone wants to require just the core SDK, at least they are fine 😃

**Comment by enumag** [comment]
@cleptric Would it be possible to make Sentry work even when `php-http/message-factory` is not installed? It can still be a dependency but that way those who need to avoid having an abandoned package in their stack could simply add it to a replace block in composer.json and force it to not install.

**Comment by ste93cry** [comment]
>The same can happen if someone uses the base SDK and requires the HTTP client manually or if it was installed via php-http/discovery.

If you're using the base SDK (and not the metapackage), then it's up to you to choose the HTTP client and install it. If you get an exception because there's a missing package that should have been required by that HTTP client, they should not complain here. What's happening here is that you're trying to solve an issue not of this package, causing complaints by all the rest of the people that are not impacted by that issue. If we can find a middle-ground solution, we should go for it.

**Comment by cleptric** [comment]
@enumag The problem is that if we remove the package again, some people will run into the mentioned exception. So currently, we sadly have to live with the lesser evil. As said, this will be resolved soon 🙂 

@ste93cry I already know you disagree, but Sentry's stance here is not to crash, even it the issue is technically not our fault.

**Comment by ste93cry** [comment]
>Sentry's stance here is not to crash, even it the issue is technically not our fault.

It's quite difficult to account for all possible bugs in technical implementations of third party packages to live up with this premise... Sometimes, being a bit more flexible is the best way to go forward 😉

**Comment by mbrodala** [comment]
So it would not be possible to have the next release of `sentry/sdk` depend on `"symfony/http-client": "^4.3|^5.0|^6.3"`? This would not be a breaking change, existing Symfony 6.2 installations will continue to work since the update won't be installed. Symfony 6.3 installations would get the update without noticing any difference. 

Also see [What should I do if I update my own dependencies without changing the public API?](https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api)

**Comment by nexik** [comment]
FYI: The next version of Composer (2.7) `composer audit` (often used in CI) will fail by default because of abandoned packages:

```
The new audit.abandoned setting (currently defaulting to "report" will default to "fail" 
in Composer 2.7, make sure to set it to "report" or "ignore" explicitly by then if you do not want this.
```

**Comment by dakujem** [comment]
@nexik Do they have some kind of a roadmap? I can't see the information anywhere.

**Comment by c-o-m-m-a-n-d-e-r** [comment]
any progress here? :-) 
thanks

**Comment by cleptric** [comment]
Yep, this was already fixed in the next major version of the SDK.

**Comment by abhibeckert** [comment]
> Yep, this was already fixed in the next major version of the SDK.

What version is that? And when will it be released?

**Comment by nicwortel** [comment]
FYI for anyone who cannot or does not want to ignore the abandoned package warnings from Composer:

If you are **not** using Symfony < 6.3, **and** you have no other packages or code depending on `php-http/message-factory`, I believe the easiest way to prevent the package from being installed is by adding the following lines to the root `composer.json` of your application (so no need to fork any packages):

```json
    "replace": {
        "php-http/message-factory": "*"
    },
```

Next, run:

```shell
$ composer update php-http/message-factory
```

This uses Composer's [replace](https://getcomposer.org/doc/04-schema.md#replace) feature to let Composer conclude that the dependency on `php-http/message-factory` is fulfilled by another package (your application), and will remove the package from your `vendor` directory.

Obviously this will break things if your code (or any of your other dependencies) actually uses any of the interfaces provided by `php-http/message-factory`, so use this with caution.

To make sure none of your dependencies depend on the package use `composer why`:

```shell
$ composer why php-http/message-factory
```

If only `sentry/sentry` is listed and you know you are not using these interfaces in your own code, you should be safe.

**Comment by cleptric** [comment]
@abhibeckert We aim for a release later this week/early next week. This will, however, only affect users who don't use our Symfony/Laravel SDK, as we will need to cut new majors there as well.

**Comment by cleptric** [comment]
[4.0.0](https://github.com/getsentry/sentry-php/releases/4.0.0) shipped and removed `php-http/message-factory`.

**Comment by ste93cry** [comment]
I still think you should release it for version `3.x` of the SDK. Not all people will immediately upgrade to the latest major and will face an error as soon as Composer starts blocking the installation of deprecated dependencies (it will happen soon). Also, as explained in my first comment, this PR should be backwards compatible, so there's no reason to insist on not merging it.

**Comment by cleptric** [comment]
> this PR **should** be backwards compatible

This is exactly the reason why I haven't merged this yet.

**Comment by ste93cry** [comment]
I was cautious, but if you read the description of the PR you will see that it's not possible to install the SDK with a version of the framework that does not support the required HTTP client.

**Comment by stayallive** [comment]
Sorry for the confusion, we shall keep this open until getsentry/sentry-symfony#783 is finished.

**Comment by cleptric** [comment]
With the release of version [5.0.0 of our Symfony SDK](https://github.com/getsentry/sentry-symfony/releases/tag/5.0.0), all current versions of our PHP SDKs do not longer require `php-http/message-factory` or any other of these packages of this kind.
