### ISSUE TITLE
PHP Fatal error:  Allowed memory size of xx bytes exhausted in GzipEncoderPlugin.php

### ISSUE THREAD

**Issue by chrisc0** [getsentry/sentry-php#1552]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

3.18.2

### Steps to Reproduce

I'm not exactly sure how to reproduce the error.  Why is one of your plugins throwing this error?

PHP message: PHP Fatal error:  Allowed memory size of 471859200 bytes exhausted (tried to allocate 65536 bytes) in /var/www/sites/xx/vendor/sentry/sentry/src/HttpClient/Plugin/GzipEncoderPlugin.php on line 53

### Expected Result

No error

### Actual Result

PHP message: PHP Fatal error:  Allowed memory size of 471859200 bytes exhausted (tried to allocate 65536 bytes) in /var/www/sites/xx/vendor/sentry/sentry/src/HttpClient/Plugin/GzipEncoderPlugin.php on line 53

**Comment by stayallive** [comment]
This is most likely because either you have a lot of information in the event (huge stacktrace, many breadcrumbs, lot's of context) and you might alreay be memory constraint which results in the application running out of memory when trying to send the event to Sentry.

Part of sending the event to Sentry is gzipping the event data since the Sentry server only accepts payloads below a certain size and the gzipping helps with staying below that limit and speeding up the network transfer too. It can be disabled by setting `enable_compression` to `false` in the SDK options, however I would suggest to be careful since that could have uninteded side effects where events might be dropped because they exceed the size accepted by Sentry.

Have you tried to reproduce the event being sent and see what data is contained within and if it might be excessively large?

**Comment by chrisc0** [comment]
How do I see what data is in the event?
Also, I tried adding another 25MB to the server but I'm still getting the error.  The frustrating part is that if I disable Sentry, my application runs just fine.  Sentry itself seems to be causing the problem here.

**Comment by stayallive** [comment]
You can use the `before_send` option to get the `Event` instance we would transmit to Sentry: https://docs.sentry.io/platforms/php/configuration/filtering/#using-platformidentifier-namebefore-send-

Since you are not using a framework it's a little tricky considering what would be in those events since you implemented them yourself it would be interesting if you can pinpoint the exact problem event to see if there might be some kind of recursive issue or if there is something interesting on the request where the problem is being triggered, like if it is a POST request with a large payload. If it's not a manually triggered event it's most likely a PHP Error like a NOTICE or WARNING (or many of them) being (attempted) to sent to Sentry.
