### ISSUE TITLE
Support modules key

### ISSUE THREAD

**Issue by mal** [getsentry/sentry-php#175]
`raven-ruby` logs gem versions to Sentry, it'd be great if `raven-php` could do the same with modules installed via composer.

If there's no nice way of getting the information from composer directly, a path setting for locating the `composer.lock` file (which stores the names and version of all installed modules) might be a good alternative.

It would also be useful to be able to include the versions of our own software.

**Comment by ste93cry** [comment]
This feature has finally been implemented in #577 and will be available since version `2.0`. The `composer.json` file will be loaded from the path configured in the `project_root` option of the client

>It would also be useful to be able to include the versions of our own software.

This can be done too by using the `Event::withModules` method. Please note that you will have to manually merge any existing value with the new one as calling that method will replace the existing data
