### ISSUE TITLE
Make max_depth for array serialization configurable

### ISSUE THREAD

**Issue by felixkempf** [getsentry/sentry-php#378]
SDK version: 1.5.0

In commit https://github.com/getsentry/sentry-php/commit/8c3e39ff8cb923195ca4aaca6f56751d99b0d8d3 the max_depth for array serialization was reduced from 9 to 3.

I think I understand the motivation behind this change, but unfortunately we loose many vital informations because of this.

Could this value be made configurable?

**Comment by dwickwire** [comment]
I second this request.  This unfortunately causes sentry to get in the way rather than to be an invisible error reporting layer, as it shows an exception for itself while reporting another exception which is too large.  We also unfortunately have information that needs to be preserved here.

**Comment by dcramer** [comment]
@dwickwire are you saying that the serialization change is causing an exception internally in our SDK?

We might consider making this configurable, but the goal here is to avoid serializing datatypes that the server is just going to throw out (in a poor way).

**Comment by dwickwire** [comment]
The exceptions are two: 1) a code exception from an intentional key value error in the code and 2) a PHP max time out, 120 seconds which comes from sentry, namely this serializer function.  

Our problem is that we have some pages which load hundreds of records and each record could trigger an exception while loading.  When sentry is not involved the same exception does not incur a PHP timeout.

I tried multiple things in hopes that we'll be able to use sentry for this project:
1. tweaking the max depth to 1
2. tweaking the max depth to 50
3. removing [some of the serializer code](https://github.com/getsentry/sentry-php/blob/master/lib/Raven/Serializer.php#L65-L71) so it would never process the recursive loop, but unsurprisingly that just creates other exceptions in Sentry.  

With 1 and 2 I still got a timeout exception, but with 1 the exception came from `SanitizeDataProcessor.php` instead of the `Serializer.php::serializer` function, big surprise I guess.

None of these attempts really addressed the issue, they all throw the max timeout exception.  Any ideas for how we can limit the size of data sentry should process or do we simply have to modify the php timeout?

**Comment by cleptric** [comment]
Any updates on this?

**Comment by dwickwire** [comment]
After manually tweaking this area of Sentry's code to simulate my own configuration parameter I noticed it would just propagate the timeout to somewhere else in the code path.  An underlying bug in our codebase was the culprit and not something was wrong with sentry's reporting.  Thus I don't need any configuration parameter any longer.

**Comment by stayallive** [comment]
This is now possible in 2.x, you can set a "custom" serializer when using the client builder. The serializer that comes with the SDK also has an `$maxDepth` option so doing something like the following should do the trick now:

```php
$builder = \Sentry\ClientBuilder::create(['dsn' => '...']);
$builder->setSerializer(
    new \Sentry\Serializer\Serializer(
        $builder->getOptions(), 
        $maxDepth = 3
    )
);
$client = $builder->getClient();
```
