### ISSUE TITLE
Duplicate sentry issues

### ISSUE THREAD

**Issue by rasmusbe** [getsentry/sentry-php#408]
When we call to an undefined function we get duplicate issues in Sentry.
One says `Error: Call to undefined function function_name()` and the other one says `ErrorException: Uncaught Error: Call to undefined function function_name()`

SDK-version is 1.6.1 and the code for initialise sentry is:
```php
if ( defined( 'RAVEN_DSN' ) ) {
	// Setup Raven with our DSN key.
	$sentry_client = ( new Raven_Client( RAVEN_DSN ) )->install();

	if ( defined( 'WP_ENV' ) ) {
		$sentry_client->setEnvironment( WP_ENV );
	}
}
```

**Comment by dcramer** [comment]
I'm not entirely sure what we should do about this. It sounds like both the error handler *and* the exception handler are getting called in this situation.

What version of PHP is this on?

**Comment by rasmusbe** [comment]
This is on PHP 7.0.13 running a [Bedrock](https://github.com/roots/bedrock) WordPress Site

**Comment by rasmusbe** [comment]
I'm still having this problem @dcramer 
For example this error came twice in sentry:
https://sentry.io/share/issue/36313432372e333335303338363037/
https://sentry.io/share/issue/36313432372e333335303338363039/

The code used for enabling logging:
```php
<?php
/**
 * Log errors to Sentry service.
 */
if ( defined( 'RAVEN_DSN' ) ) {
	// Setup Raven with our DSN key.
	$sentry_client = ( new Raven_Client( RAVEN_DSN ) )->install();
	if ( preg_match( '/\\/(\\d{14})\\//', __DIR__, $matches ) ) {
		$sentry_client->setRelease( $matches[1] );
	}

	if ( defined( 'WP_ENV' ) ) {
		$sentry_client->setEnvironment( WP_ENV );
	}

	$sentry_client->setAppPath( dirname( __DIR__ ) );
}
```

**Comment by stayallive** [comment]
@rasmusbe just to be sure, are you still on Raven `1.6.1`? If so can you update to `1.7.1`, I thought there were some changes to prevent this but I cannot find the commit right now. 

If you are already up-to-date I will try to recreate this locally so I can try to recreate it.

**Comment by rasmusbe** [comment]
Thank you, already updated to 1.7.1 unfortunately.

**Comment by stayallive** [comment]
I am noticing this behaviour too. Both the `handleException` and `handleFatalError` are triggered (which is correct since it is an fatal error -> crash), both with a different exception object (the first being nicely formatted and the second just an exception we create for the error: https://cld.bouma.me/3L281j3H0q0L).

@Jean85 @dcramer do you have an idea on how to solve this. 

We could possibly ignore the fatal error if the exception (in the samen line/file) was already reported although that does feel a bit hecky IMHO.

**Comment by Jean85** [comment]
Maybe we can intervene in the `ErrorHandler::shouldCaptureFatalError($type)` and inject logic to avoid capturing fatals if we are under PHP 7, where they are thrown as `\Throwable`s? I'm not sure if that will cover all the use cases...

**Comment by stayallive** [comment]
@Jean85 so for PHP 7+ we could then remove the `E_ERROR` (or ignore the `E_ERROR`) from the `$fatal_error_types` since those already went through the Exception handler, right?

Since we are rethrowing the error instead of returning true from our exception handler (so the native handler can take over and log it to the error log) we cannot guard against it earlier.

**Comment by stayallive** [comment]
With version `1.8.1` just released, this should be fixed. If it still persists for anyone, please open an new issue with some info on the error that is duplicated.
