### ISSUE TITLE
We don't have PHP 5.2 support

### ISSUE THREAD

**Issue by nokitakaze** [getsentry/sentry-php#437]
We already don't have PHP 5.2 support

I wanted to fix some error what I made but then I found this
![default](https://cloud.githubusercontent.com/assets/9131758/24330117/91ea30d8-1220-11e7-91a0-7303f47760ac.PNG)
So no one can do "composer tests".

![gwbmloy 1](https://cloud.githubusercontent.com/assets/9131758/24330099/421bff64-1220-11e7-8dec-60372752758f.png)

https://packagist.org/packages/friendsofphp/php-cs-fixer
```
requires php: ^5.3.6 
```

https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.13/Symfony/CS/Fixer/PSR2/EofEndingFixer.php#L43

**Comment by ste93cry** [comment]
It seems @JellyBellyDev made a fork with changes to work on PHP 5.2: [immobiliare/sentry-php](https://github.com/immobiliare/sentry-php). What about merging the changes here?

**Comment by nokitakaze** [comment]
https://github.com/immobiliare/sentry-php/blob/master/composer.json#L19

https://packagist.org/packages/friendsofphp/php-cs-fixer#v1.8
> **requires**: php: >=5.3.6

It's funny

**Comment by ste93cry** [comment]
It seems that the changes only involves the code of the SDK itself, not the dependencies. Plus, there is no compatible version of PHPCS with PHP 5.2. Although fork is not tested on Travis with that version of PHP, if it works it's better than nothing

**Comment by nokitakaze** [comment]
I think it is the only incompatible string with closures
https://github.com/getsentry/sentry-php/blob/master/test/Raven/Tests/ClientTest.php#L1067

**Comment by JellyBellyDev** [comment]
Hello guys,
php-cs-fixer and phpunit requires php >= 5.3.
Also travis does not support php5.2.
In a nutshell, is impossible to test the sdk with php52 in automatic.
In our fork we simply made the appropriate fix on sdk to work with PHP5.2 doing manual testing. :sweat:
We love sentry and we hope we have done a good thing, for those of us wants to make it work even in PHP5.2

**Comment by nokitakaze** [comment]
Why do you still use this version?

**Comment by JellyBellyDev** [comment]
Because the legacy never dies! 😄

**Comment by Jean85** [comment]
The fact that PHP-CS is not 5.2 compatible shouldn't be an issue. 
The fact that the codebase isn't, or that Travis doesn't support it, should.

Apart from that, upping the required version to 5.3 should only create issues to end users, since their Composer would only fall back to the previous, unfixed version, so we should fix this in the codebase. Also, the minimum PHP version is being bumped already in the 2.0 branch.

**Comment by Jean85** [comment]
@JellyBellyDev could you open a PR from your fork to our master to fix this issue?

**Comment by JellyBellyDev** [comment]
You say it could be accepted?
I've read some issues a while ago, did not seem interested in maintaining compatibility with 5.2.
Am I wrong?

**Comment by Jean85** [comment]
Umh, I've reviewed the differences, and I've changed my mind about this, sorry: it seems to me that the diffs are too small and mainly cause compat/conflict issues... The PR (and the consequent merges)  would be more work than eventual benefits. Since we are also dropping younger PHP versions with the 2.0 development, maybe we shouldn't change anything about this.

If @nokitakaze and @ste93cry agree with me, I think we should close this as wont-fix.

**Comment by nokitakaze** [comment]
> I think we should close this as wont-fix

There is no problem with Sentry does not support PHP 5.2. There is problem with Sentry does not support PHP 5.2, but declares it do.
https://github.com/getsentry/sentry-php/blob/master/composer.json#L20

**Comment by Jean85** [comment]
I completely agree. I would suggest a PR with a bump to 5.3, and an addition to the readme pointing to the fork, so troubled users would know how to solve this issue.

**Comment by JellyBellyDev** [comment]
If you want, I can do it.

**Comment by Jean85** [comment]
@JellyBellyDev I did it already, thanks.

**Comment by nokitakaze** [comment]
I do not know how to test compatibility with PHP 5.2. I could install old Ubuntu and PHP, but I don\'t want to write tests for such old version
