### ISSUE TITLE
Sentry fills up the logs, breaking site

### ISSUE THREAD

**Issue by Luke-SF** [getsentry/sentry-php#499]
Autoloader calls `ini_set('unserialize_callback_func', 'spl_autoload_call');`

If ini_set is disabled for security (as many sites do), and warnings are set to go to the log file (as most sites will likely have set), and Sentry runs on most/all requests (as it should), it will fill up the log and break if there is no log-rotate or clearing functionality set up.

Why not set @ in front of the ini_set?

**Comment by stayallive** [comment]
I think it has gone unnoticed since most people either disable warnings or have `ini_set` available.

We would have to make sure we can safely ignore the warning and maybe remove the ini_set alltogether because we might be able to solve this another way (or it's not needed anymore alltogether).

This seems to be one of the more fun php quirks 😄  https://stackoverflow.com/a/2405422/1580028

Will dig into this!
