### ISSUE TITLE
Directory 

### ISSUE THREAD

**Issue by Luke-SF** [getsentry/sentry-php#519]
The instructions in https://sentry.io/for/laravel/ say to add to config/app.php and App/Exceptions/Handler.php

However that Handler.php doesn't exist in all version of Laravel... I don't see it anywhere.
In Exception/Handler.php mine doesn't have a function report(), either.

**Comment by Jean85** [comment]
I suggest you to look at https://github.com/getsentry/sentry-laravel.

Also we should ping @stayallive which should know about the Laravel integration better than me... Maybe the docs on the site are off-sync with this repo?

**Comment by stayallive** [comment]
Hey @Luke-SF, every 5.x install of Laravel comes standard with that file and a render method (https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php#L49) however, it is possible to remove that method or even move the exception handler class since everything is customisable.

But let's start at the beginning, on what version of Laravel are you? Since Laravel 4.x is another story :)

**Comment by stayallive** [comment]
Closing this issue because it is quite old, if there is still a problem please open a new issue.
