### ISSUE TITLE
Is it OK to use multiple Raven_Client objects on same page

### ISSUE THREAD

**Issue by s-nizamani** [getsentry/sentry-php#524]
We are trying to use sentry in our code and documentation is really easy way we want to implement sentry is we can add error listener like this:

```php
$client = new Raven_Client('https://<key>:<secret>@sentry.io/<project>');
```

Above line has to go in the very first file in our MVC so we can use `$sentryClient->captureMessage('my log message');` later in our code but this will create a global variable `$client` which can be overridden easily in our code by mistake. I know sentry recommends doing this:

```php
$error_handler = new Raven_ErrorHandler($client);
$error_handler->registerExceptionHandler();
$error_handler->registerErrorHandler();
$error_handler->registerShutdownFunction();
```

But this will also create two global variables so my question is, is it ok to use multiple sentry objects in our code so we can do something like this without creating any global variables and still use sentry in very first file of our MVC:

```php
(new Raven_Client('https://123@sentry.io/258481'))->registerExceptionHandler();
(new Raven_Client('https://123@sentry.io/258481'))->registerErrorHandler();
(new Raven_Client('https://123@sentry.io/258481'))->registerShutdownFunction(); 
```

**Comment by Jean85** [comment]
I'm missing why should you declare it as a global variable... You need to store it somewhere, but yes, global is not the way to go IMHO and it shouldn't be required.

**Comment by stayallive** [comment]
You need to call it from somewhere and putting it in the very first file (index.php) makes it available to every included file thereafter (which makes it look like it's global).

I would not recommend doing 3 clients since each client also does work and uses memory (which slows down your request). Also the breadcrumbs/context functionality will not work correctly like that.

If there is no dependency container you are using in your application _maybe_ something like this could be considered instead of just defining `$client` somewhere in your application and possibly overwriting it as you mentioned yourself already.

```php
function sentry_client()
{
	static $client = null; // No this does not assign null every time the function is called, only the very first time

	if ($client === null) {
		$client = (new Raven_Client('http://public:secret@example.com/1'))->install();
	}

	return $client;
}
```

Which you should call as early as possible so it runs `install()` (but because of the static var only once per request) and can use in other files like:

```php
sentry_client()->captureException($e); // Or any other method on the client
```

But again, if you are using some kind of framework or other ways to pass objects around like a DI container or other global storage I would leave a `Raven_Client` instance there, this way breadcrumbs and context functionality of the client will remain intact. But if that's no a possibility the function above might help.

**Comment by s-nizamani** [comment]
Thanks @stayallive install will run all methods that we need for auto error catching. We will consider using function as shown in your example or class method if we need to create global sentry object like you mentioned

**Comment by Jean85** [comment]
Closing as resolved.
