### ISSUE TITLE
Sentry silently failing with HTTP 413 Payload Too Large

### ISSUE THREAD

**Issue by ArondeParon** [getsentry/sentry-php#529]
I was wondering why certain events were not being reported to Sentry.

After digging into the SDK, it seems that `captureException` is silently failing because the server returns a HTTP 413.

Some questions:

1. What can I practically do to keep my error objects smaller?
2. Should Sentry silently fail? This seems a bit confusing and it took me quite a while to figure this out.

**Comment by Jean85** [comment]
Have you changed the serializers? What version of the client are you using? Are you using any (official) integration?

**Comment by ArondeParon** [comment]
Hi @Jean85,

We're using the https://github.com/getsentry/sentry-laravel package, version 0.8.0. We haven't made any customizations to the serializers and we don't pass any extra information, so it's pretty much an out-of-the-box install.

**Comment by Jean85** [comment]
What's the version of `sentry/sentry` that are you using? Latest versions should have some countermeasures to reduce the payload, if that isn't enough we should try and see what data is so big that it's exceeding Sentry's limits...

Also, ping @stayallive

**Comment by ArondeParon** [comment]
We're using 1.8.2, so I believe that these countermeasures are already in place... If you want me to send the data, please let me know at which stage we should intercept it. I'm probably going to need some time to do some obfuscation as well if I were to post it here.

**Comment by stayallive** [comment]
You could add a `send_callback` using the `sentry.php` config file (you cannot use config:cache if you add this since it cannot cache closures).

```php
return array(
    'dsn' => '',

    // capture release as git sha
    // 'release' => trim(exec('git --git-dir ' . base_path('.git') . ' log --pretty="%h" -n1 HEAD')),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => true,

    // Capture default user context
    'user_context' => true,

    'send_callback' => function($data) {
        app('log')->info('Sentry payload: ' . json_encode($data));
    },
);
```

This should log every payload (encoded as json), it would be very helpful to at least know how big it is or where the largest data is (variables or body or breadcrumbs or the stack) so we can try and figure out what is happening. Also useful to know if you are running into this problem for a normal web request (GET/POST) or in an artisan command / queue?

If you could share the full `$data` that would be even better, but I can understand that contains a lot of private data so the above indicators could possibly help us replicate.

Thanks for all the effort!

**Comment by ArondeParon** [comment]
Hi @stayallive thanks for the pointers!

I did some debugging using the callback and see that the errors are being caused by the "context" that is being sent with the error report. In the cases I'm looking at, there are some pretty large collections of objects being passed around in memory and these collections are added to the context.

**Comment by Jean85** [comment]
In this case, I suggest you to prune that context, since there are a lot of hard limits on how much stuff can be sent to Sentry. Limits are listed in the [official documentation](https://docs.sentry.io/learn/quotas/#attributes-limits).

I'm closing this as resolved, but feel free to continue replying if needed.

**Comment by ArondeParon** [comment]
Alright, thanks!

Perhaps there could be some kind of mechanism to detect these http 413 errors, at least? The only place where it registered is in the `$_curl_instance` variable, which is protected. There is `getLastError()` as well. In the case of a HTTP 413 this variable contains an empty string. Since the default is `null`, this can be used to detect errors, but it's still pretty hard to know what exactly went wrong.

**Comment by SwiTool** [comment]
@ArondeParon 

Could you please tell in what file you added the above code ? Thanks

**Comment by ArondeParon** [comment]
> @ArondeParon
> 
> Could you please tell in what function you added the above code ? Thanks

At that time I added it to the `report()` function in the `Handler.php` file. I believe that the recommended way nowadays is to add a reportable callback in the `register()` method of that same file now, though:

use Sentry\Laravel\Integration;

public function register()
{
    $this->reportable(function (Throwable $e) {

        // Add custom breadcrumb stuff here...

        Integration::captureUnhandledException($e);
    });
}

**Comment by SwiTool** [comment]
Thank you, I appreciate you answered 5 years later !
