### ISSUE TITLE
Sentry not displaying local vars value

### ISSUE THREAD

**Issue by aluferraz** [getsentry/sentry-php#530]
Hi there,

Sentry is no longer showing me the values of local vars:

![image](https://user-images.githubusercontent.com/5156410/34851751-9f3b830e-f712-11e7-99df-0a91f4b2c3ab.png)

Shouldn`t this be available in the details of the issue?

**Comment by dcramer** [comment]
It's only available if it wasn't truncated (due to size of payload) and/or was sent. As you can see in this screenshot 'request' is shown below, so its possible the values were not present or simply were truncated. Unfortunately thats not super easy to investigate, but usually is obvious because theres a lot of other data going on.

I'm also assuming nothing else changed (e.g. an upgrade to sentry-php, though that should be well tested).

If this is on sentry.io you can probably ping support with the account details and we might be able to see if something else might have gone wrong in logs, but likely little to no info there.
