### ISSUE TITLE
Minimum PHP version of 7.0 for 2.0 release

### ISSUE THREAD

**Issue by MarioBlazek** [getsentry/sentry-php#539]
Is it possible to support only PHP 7 in version 2.0 ? Do we have any valid reasons to stay with PHP 5.6 ?

**Comment by Jean85** [comment]
2.0 is already bumping a lot in terms of minimum supported version, currently we support 5.3+.
This was discussed at long [here](https://github.com/getsentry/sentry-php/issues/424#issuecomment-284283900).

The point is that the Sentry userbase has a lot of projects that are on older versions (there's even [a fork for PHP 5.2](https://packagist.org/packages/immobiliare/sentry-php)!) so being too drastic in terms of minimum language version required was considered not feasible.

2.0 is currently in development but it should be near its completion, switching minimum supported version right now could just delay the release a lot, since we would have to reconsider a lot of stuff. IMHO we should wait for a 3.x, where the bump could go up even to 7.1, where having `void` and nullable type hints could be a real benefit.

**Comment by stayallive** [comment]
Let me know if you have any other concerns but @Jean85 explains very well why the decision was made for 5.6+ and not 7.0+.

**Comment by MarioBlazek** [comment]
@Jean85 @stayallive thank you both for clarification.

**Comment by jsmmo** [comment]
Hey, I just wanted to point out that the dependency chain of the package is not supporting 7.0 anymore. I want to speak up for old php version since error managing is a topic where migration paths are important.
Do you guys plan supporting old php versions? Its very important to us. Its not about your package. The dev dependecies are requesting 7.1 but its not needed. We had to fork it....

**Comment by ste93cry** [comment]
PHP 7.1 is required as we're using some features introduced with that version. Also PHP 7.0 is one year old more or less, so if you're using it you're using an unsupported version that may not only have unfixed bugs but also unfixed security issues. Said this, even though we're not actively developing the `1.x` branch anymore that version should more or less still be compatible with PHP 7.0 :wink:

**Comment by Jean85** [comment]
FTR, we changed that decision since #670: we had lengthy discussion about this topic, and the PHP ecosystem moved a lot forward in the meantime, so it seemed to us that PHP 7.1+ was a good balance between nice language features and a wide support, also because 1.x is still a working client for older PHP versions, if needed.
