### ISSUE TITLE
Fatal error: Maximum execution time of 30 seconds exceeded in sentry-php-master/lib/Raven/Serializer.php on line 73

### ISSUE THREAD

**Issue by binary64** [getsentry/sentry-php#568]
Hi, I'm not sure what causes this error. Maybe a cyclic reference in an object?

**Comment by Jean85** [comment]
The line reported in the error may not be the culprit itself, it's just the line where the script stopped due to a timeout.

Cyclic references shouldn't matter here, since the `serialize()` method has a max dept argument. If you didn't alter the limit, the only possibility is that you were serializing a very large object.

**Comment by binary64** [comment]
Indeed it was a very large object caused by another bug. Let's close ticket unless you think there should be a sane limit to the size of the object serialized.

**Comment by stayallive** [comment]
I am not sure if there is very much we can do about is unless indeed limiting it. However that would also depend on how big you memory limit is and if the error we are dealing with is an memory limit error since there will be less memory available.

IMHO this is an edge case, but happy to discuss ideas on how to prevent this possibly if needed.
