### ISSUE TITLE
Discarded invalid value for parameter 'timestamp' 

### ISSUE THREAD

**Issue by erichard** [getsentry/sentry-php#580]
Sentry.io is discarding this parameter. The value is constructed with `gmdate()` in `Client.php`. Maybe we  need a real timestamp here.

**Comment by ste93cry** [comment]
As far as I know it always worked fine, the same line of code is reused in version `2.0` and I never noticed that error message. Maybe something changed in newer versions of the server? ping @dcramer

**Comment by dcramer** [comment]
Anyone happen to have the output thats being discarded?

**Comment by erichard** [comment]
![capture du 2018-04-10 19-00-10](https://user-images.githubusercontent.com/651041/38571676-aeff1896-3ce0-11e8-820d-6e53083bc2f0.png)

I get that in all events

**Comment by Jean85** [comment]
@erichard what version of the client are you using? Are you using any integration?

BTW that line of code is unchanged since 3 years ago! https://github.com/getsentry/sentry-php/blame/master/lib/Raven/Client.php#L828

**Comment by alex-hofsteede** [comment]
Hmm, the timestamp you posted does seem to validate fine with the current logic. It's possible that there is a clock skew issue somewhere that is causing the timestamps to be too far in the future to be accepted (currently we reject timstamps more than 1 minute in the future) 

I created https://github.com/getsentry/sentry/pull/7997 to change the error message so that the past/future issue is distinguishable in the error message from a plain invalid timestamp.

**Comment by Jean85** [comment]
Thanks @alex-hofsteede!!
Closing here as it seems something serverside. Feel free to reply here if there's anything else to discuss.

**Comment by alex-hofsteede** [comment]
@erichard is there any chance that you can post the `"received":` value from the sentry UI (in the event JSON) for that event? I'd like to confirm the hypothesis that the timestamp is being rejected because it is too far in the future, and comparing the timestamp and the received value should tell me if that's the case.

**Comment by alex-hofsteede** [comment]
Yeah that received time is `2018-04-11T05:38:50Z` so the timestamp being reported to the API is about 2 minutes ahead of the server time.

In any case, the API defaults to using the current time for these future timestamps, so there's not really any negative effect, aside from the error message which shows up in the UI. (which should at least now say `Invalid timestamp (in future)` since getsentry/sentry#7997 shipped)
