### ISSUE TITLE
Some issues missing variables as well as Headers and in some cases POST data

### ISSUE THREAD

**Issue by archon810** [getsentry/sentry-php#582]
Hi,

I'm opening this ticket so we can discuss it directly with engineers without involving support. I'll summarize the issue here based on what I sent to support, though omitting the individual event urls (Sentry devs can see those in the support ticket).

> I've been observing a really annoying issue with Sentry not reporting any variables and I'd finally like to get to the bottom of this.
> 
> For most of our Sentry entries, there is variable information and values all filled in. That's nice.
> 
> But for a subset, like Wordpress WP Cron errors, there are never any variables.
> 
> Why would this be and how can we fix it?
> 
> Support suggested this only happens with POST requests, which I think they're right about. I then noticed that some issues are not only missing variables, but also missing the POST data which is present in some other POST requests I've seen (or if POST data is too big, maybe Sentry can show at least a chunk of it to see what was being POSTed - this would be tremendously useful if someone is probing for security holes - otherwise we're basically blind to these things). Also, in some cases there are no Headers at all, which is odd.
 
I'm using the latest Sentry 1.8.4 release.

Thank you.

**Comment by stayallive** [comment]
Hi @archon810, let's get to the bottom of this because this is not supposed to happen.

I am checking if it is a Sentry server thing discarding data and seeing if we somehow can detect / see that that is happening.

Could you tell us on what PHP version this is happening, on `>7` we have a issue where some fatal errors (not exceptions) are reported twice and the second report is missing a lot of data (since it's simply not available) this could also happening `<7` and then there won't be a "nice" report. 

But wanting to see on what PHP version I need to be looking before testing anything 👍

**Comment by archon810** [comment]
We're on PHP 7.2.

**Comment by archon810** [comment]
Are you able to look at our data in sentry? I'm giving you permission for the purposes of resolving this bug. The php version is also shown there (7.2.4). You can find the links in my support interactions with Kelly.

**Comment by stayallive** [comment]
That was a fast reaction, thanks, that simplifies looking 🥇 

---

Could you also tell me what kind of errors are reported without vars?

Are that memory problems or exceptions thrown from your code, some patterns with specific errors (only CLI, only fatal errors, only your own exception, only warnings etc.)

---

(if you already sent some errors to be viewed to support I can ask for details privately through support)

^ I see you did, I will ask Kelly for the details and get back to you here!

**Comment by archon810** [comment]
@stayallive I see you already saw some details. Do you need anything else from me? I think the most obvious pattern that I see is POST requests.

**Comment by archon810** [comment]
And yet I see some POST requests that are ErrorExceptions that do have vars (how can I pass them to you privately?).

Yet other POST requests that are also ErrorExceptions don't.

OK, now I see the ones that don't have variables are ErrorExceptions that are red, not orange or blue, and are caught by handleFatalError as opposed to handleError. Is it possible to recover all this missing data for fatal exceptions?

**Comment by stayallive** [comment]
@archon810 yeah I same 2 one with and one without vars. Thu current theory is that it's only for fatal exception like exceeding the maximum execution time or a memory limit (which are usually POSTs however this happens also with GETs).

Those errors do have a stacktrace but no extra info causing vars to be missing.

**Comment by archon810** [comment]
@stayallive So is this a PHP bug that needs to be or has been reported directly to PHP or there's a way to get those some other way? What is the solution?

**Comment by stayallive** [comment]
@archon810 since we only have the information [error_get_last](http://php.net/manual/en/function.error-get-last.php) is giving us when a fatal error occurs (out of memory or when the max execution time is reached) there is no way to get the variables passed to a function. since there is no backtrace.

PHP simply doesn't provide it and could also result in huge traces / variables in case of memory and/or execution time errors.

I think there is no way around this for fatal errors.

We do however [still capture the post variables](http://f.bouma.me/v/VjVBSH4imn7rk9q2ptCj) on fatal errors which could help.

**Comment by archon810** [comment]
Perhaps PHP could provide a configurable buffer for such cases which would contain the variables and the stack trace, even if the exception was fatal and caused by OOM. FatalExceptions are some of the most egregious and hard to debug because they're serious and lack information, so it's more important to be able to see vars for them than for simple notices.

Shall we suggest it to the PHP team in their tracker perhaps and see where it leads? You can point them to this thread.

**Comment by stayallive** [comment]
You are ofcourse very welcome to make any proposal to the php team.

I will close this issue for now since it’s something we are unable to overcome since stacktraces are not that detailed on fatal errors from the language side. If something changes or new ideas to do this are created/discovered we can rediscuss.

**Comment by archon810** [comment]
@stayallive I've filed a bug/feature request with PHP here https://bugs.php.net/bug.php?id=76274.

Please chime in with any extra knowledge that you may have about where exactly the information is missing, as you're much more familiar with how Sentry works.

**Comment by mfb** [comment]
see also https://stackoverflow.com/a/26339787/516355
