### ISSUE TITLE
Deprecated message are not logged

### ISSUE THREAD

**Issue by ragusa87** [getsentry/sentry-php#605]
Hello,

I have a problem with the raven_client using Symfony.
On Symfony, deprecated messages are shown on the profiler toolbar, so it's possible to view and fix them.
Using the sentry-symfony bundle, all the deprecated messages are gone once the bundle is registered.
The problem comes from the error handlers installed by the raven client and is not related to the bundle itself (See https://github.com/getsentry/sentry-symfony/issues/120)

I found out that once the raven client is installed, the deprecated message are not displayed anymore.

## How to reproduce the problem:
> Install Symfony 2/3 (I haven't tested it on symfony 4).
> require the sentry bundle ("composer require "sentry/sentry")

Open the DefaultController::indexAction and add this line:
```php
@trigger_error("Test deprecated warning", E_USER_DEPRECATED);
```
Once the page http://localhost/app_dev.php has been refreshed, you should see the warning:
![image](https://user-images.githubusercontent.com/1695207/40538265-8b126ee8-6011-11e8-8c29-fb8e8f9fe0c8.png)
You can open the profiler to get more informations:
![image](https://user-images.githubusercontent.com/1695207/40538326-b5172724-6011-11e8-99c1-b36435b8ba36.png)
Then register the Raven_client by adding theses lignes ~~before the trigger_error~~: on AppBundle:boot() method;
```php
class AppBundle extends Bundle
{
    public function boot(){
        $r = new \Raven_Client();
        $r->install();
    }
}
```
Now the deprecated message is gone:
![image](https://user-images.githubusercontent.com/1695207/40538470-0ea458ca-6012-11e8-8d98-4c7b79add36a.png)

Thanks for your help !

**Comment by stayallive** [comment]
Hey @ragusa87, first I would like to point out that enabling Sentry in dev is not a good idea since it's meant to catch and report errors, if you have other means for that (Symfony profiler bar etc.) you should not need to enable Sentry :)

This "issue" is possibly in how the `handleError` function works in the SDK which returns true after it handled the error (indicating it handled it) and Sentry registers it's handler before the profiler does.

Normally Sentry takes the "old" error handler and executes it after it handled the error, but if Sentry is the first error handler the old handler is never called and the profiler might see that another error handler already handled the error and thus should ignore it... however I am not familiar with the Symfony profiler and how it registers / reads those errors.

Hope this helps searching for the root cause, I am not at all familiar with Symfony but hopes these remarks help solving it 👍

**Comment by ragusa87** [comment]
Thanks for your answer,
It seems that if the Raven handlers are registered before the Symfony one, the deprecated messages are gone, but it works the other way around. So it's seems that we can find a workaround on the sentry-symfony bundle.

It's common to load the symfony-bundle in every environment and set the DSN only for production (in config_prod.yml), in this case, errors are not send to sentry due to an empty DSN but the deprecated messages are gone as the raven handler are registered. At least I have seen this config in many projects.

Thanks for your remarks, it was helpful.

**Comment by ste93cry** [comment]
This could also be related to getsentry/sentry-symfony/issues/130
