### ISSUE TITLE
"Call to a member function cool2() on integer" uncaught for some reason.

### ISSUE THREAD

**Issue by bs-thomas** [getsentry/sentry-php#656]
Hello there,

I have the following code.  For some reason, I'm not getting the error report for this on Sentry platform.

```
        $client = (new \Raven_Client("https://{$publicKey}@sentry.io/{$projectId}"))->install();
        $b = 2;
        $c = $b->cool2();
```

On the screen, I get this exception.

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function cool2() on integer

I confirm that other errors (such as division by zero) are thrown without issues.
I'm using sentry/sentry 1.9.2

I'm still on localhost, Windows 10, Wamp, PHP 7.0.10

Your help is appreciated.  Thank you!

**Comment by bs-thomas** [comment]
Oh, I noticed something!

If I do the same thing before I step inside the framework (right after the autoload include) (I use Laravel btw), it actually gets caught by Sentry!

Hmmm, I think I'm misunderstanding some key concepts here.

If someone would be able to shed me some light, I'd be very much appreciated!

Thank you!

**Comment by bs-thomas** [comment]
Sorry for spamming so many comments.  I know I should've summarized everything at once.

I know there is a Sentry library for Laravel.  However, I want to keep my custom code loosely dependent on Laravel, so I prefer using the native PHP version of it.  However, if setup is so complicated, I definitely will consider the Laravel version of it.  I want to just know what's running behind before I make the decision.

Thanks again!

**Comment by stayallive** [comment]
Hey @bs-thomas, if you are seeing the error in your browser (in the nice error page Laravel provides) I think it's catching the errors before sentry can so they're never submitted.

I would consider trying the Laravel package, it's just a simple wrapper on the Sentry client, so any code written integrating with Sentry directly is easily changed to any framework or project (you interact with the Raven_Client directly through the Laravel integration).

So it's probably because of a loading/registering order of the error catching in Laravel & Sentry. Also try setting your debug to false en env to production to make sure no local debug things are shown/handled.

**Comment by bs-thomas** [comment]
Thanks for the assistance.  Indeed using the sentry-laravel package is a lot simpler.  I don't have to worry about the weird exceptions caught by the framework.  Thanks for your assistance!
