### ISSUE TITLE
Error handler context deprecated

### ISSUE THREAD

**Issue by mindplay-dk** [getsentry/sentry-php#662]
The context argument for error-handlers was depreacted in 7.2, and probably should be removed?

I've [asked](https://externals.io/message/103300) on the PHP internals mailing list, and, sadly, it doesn't sound like they were planning on offering any alternative to this feature.

**Comment by Jean85** [comment]
I've done a little bit of digging here and there, and luckily this seems a non-issue for us! :tada: 

In the 2.0 branch that argument is not used:
https://github.com/getsentry/sentry-php/blob/2.0/src/AbstractErrorHandler.php#L157

...since the only variables values that we send are function arguments, which are taken using `debug_backtrace`:

https://github.com/getsentry/sentry-php/blob/2.0/src/Stacktrace.php#L77

So, yay! Thanks for digging this up anyway, your help is appreciated.

**Comment by mindplay-dk** [comment]
2.0 branch?? Hello! doc-blocks, type-hints, abstractions, dependency-injection! nice! 😄👍 

Closing this issue, thanks.

Any idea when 2.0 will be ready?

I'm integrating Sentry into a very modern PHP stack with PSR-7/15/17 middleware etc. and the current version is not a very good fit. This looks promising!

This looks substantially different, so I probably shouldn't spend a lot of time working the old version into our stack?

Is it far enough along that it would make sense to start testing and integrating version 2 instead, do you think? We don't expect to need this in production before March'19. I might be able to provide you with some useful feedback.
