### ISSUE TITLE
escapeshellarg(): Argument exceeds the allowed length of 2097152 bytes

### ISSUE THREAD

**Issue by adhocore** [getsentry/sentry-php#730]
we frequently have this error/issue popping up for potentially large backtrace.
apparently `escapeshellarg()` doesnt support long string input.

```
ErrorException vendor/sentry/sentry/lib/Raven/Client.php in handleFatalError at line 1153

escapeshellarg(): Argument exceeds the allowed length of 2097152 bytes
```

a possible solution is instead of native `escapeshellarg()`, maybe we can manually replace single quotes `'` with the escaped version

we use sentry v1.10.0 and php7.2

**Comment by ste93cry** [comment]
quoting from the [PHP documentation](http://php.net/manual/en/function.escapeshellarg.php), `escapeshellarg` escaping rules are different from OS to OS:

>escapeshellarg() adds single quotes around a string and quotes/escapes any existing single quotes allowing you to pass a string directly to a shell function and having it be treated as a single safe argument.
>
>On Windows, escapeshellarg() instead replaces percent signs, exclamation marks (delayed variable substitution) and double quotes with spaces and adds double quotes around the string. 

So we can't just drop the usage of that function and manually replace the characters. The best solution I can suggest is to switch the send method to `async` instead of `exec` which have been anyway removed from version 2.0 of this library (which is in beta since a few days)

**Comment by adhocore** [comment]
thank you for the pointer. is v2 production ready already or anytime soon? we are all fine to bump the version.
in the meantime we will use async. we however dont know how the performance compares with exec.

**Comment by ste93cry** [comment]
Since `2.0` has currently been released as beta version I can't say that is production ready, however the API should be pretty stable and I don't expect any big change coming soon but only bug fixes. I also expect to release the stable version ASAP, but to be honest AFAIK there are no users using it yet so you may be the first or one of the first guys trying the new SDK with all that follows

**Comment by ste93cry** [comment]
Just to let you know, `2.0` has been released as stable. In case you want to continue using a process to send events to Sentry, you may want to have a look at the [Symfony Process](https://symfony.com/doc/current/components/process.html) component and write your own transport. I don't know however if it can help with your main issue of the maximum length. I'm going to close this since anyway we are not willing to implement such transport out-of-the-box
