### ISSUE TITLE
Is it possible to implement Sentry just for a plugin?

### ISSUE THREAD

**Issue by vyskoczilova** [getsentry/sentry-php#764]
Hi, do you think that would be possible to limit Sentry just by namespace, or specified files I'd like to watch? We have a WP plugin It would be great to track the potential problems with Sentry, but we don't want to get a ton of unfixable data from another plugins, theme, WP itself... just only when it occurs within our plugin - a couple of files installed across many websites.

Thanks a lot and cheers for a great job!
Karolina

**Comment by stayallive** [comment]
I think right now there is only one way to do this. 

You can supply a callback to `before_send` and exclude it based on the information you find in the Event instance (for example check the last frame of the stacktrace to see if that is in your plugin path) that is passed there.

```php
\Sentry\init([
    'dsn' => 'https://sentry.io/...',
    'before_send' => function (\Sentry\Event $event) {
        // return `null` if the event should not be sent
    },
]);
```

However be careful with doing this since the SDK can only be initialized once and could conflict with earlier installations (overwriting them). So you might want to detect if Sentry is already used in the WP project where the plugin is installed.

**Comment by HazAT** [comment]
Also in addition to what @stayallive said:

Are you expecting any global "unhandled" errors/exceptions?
If not it would be the simplest if you just create a `Client`, set your DSN catch your errors and send it off with `captureException`.

**Comment by ste93cry** [comment]
Just my two cents: I don't have the full context of your job/company and what it does, but let's suppose that you are a plugin developer and you're releasing your plugin to the world. It would feel strange and weird if I install and enable it and then I find out that it's reporting errors to someone else. You may be a web agency (e.g.) and the plugin would be specifically applied to a client's project and then it would be ok to track errors, but if you're planning to use it in a public plugin/theme I advise against it

**Comment by vyskoczilova** [comment]
You are absolutely right. I would use it just within the test phase of the plugin, so everybody will know about it. Let's say, 10-20 websites before it will go to the wild. However, It would be time-consuming to go over every false positive report handled on the website.

**Comment by ste93cry** [comment]
I'm closing this since it seems that the problem has been solved. Feel free to reopen if you still have issues
