### ISSUE TITLE
Replacement for `curl_method` option in Sentry 2.0.1

### ISSUE THREAD

**Issue by Shylajhaa** [getsentry/sentry-php#796]
Is there an alternative for the `curl_method` key in options array used while initializing the Client

**Comment by Jean85** [comment]
Since we're now using HTTPlug, it may depend on which HTTP client you're using. If you installed `sentry/sdk`, you're still using Curl, so you can di it directly on your own on the client.

In any case, you have to do that on the `ClientBuilder`, so you can build a `Client` with the modifications of your choosing.

**Comment by Shylajhaa** [comment]
So the requests will be asynchronous?
In the previous version, I used `curl_method = async`

**Comment by ste93cry** [comment]
Requests will not be really asyncronous because async is not supported in PHP. Async here means that flying HTTP requests will be executed in parallel by cURL. However they will still block the execution flow, there is no way around other than using something like [reactphp/react](https://github.com/reactphp/react) and stop sending events directly from the request (e.g. using the spool transport)

**Comment by mfb** [comment]
Well, it is possible to use PHP socket streams to send out non-blocking requests in a fire-and-forget manner, i.e. sending the request and disconnecting without waiting for a response.  You can use this technique to talk to external APIs when the response is not important and you don't care whether or not the request succeeded. For example, if some content is updated and you need to flush caches in the CDN, you can quickly send some non-blocking purge requests to the CDN's API.

**Comment by Jean85** [comment]
That still is a transport concern: you should act on your transport to let it behave like that; since Curl is supported (and even suggested), you can work on that.

**Comment by ste93cry** [comment]
As @Jean85 said, since the transport is now customizable entirely you can choose whichever HTTP client to use, be it cURL, Guzzle or whatever else. In turn this can be synchronous or asynchronous. In version `1.x` the option `curl_method` existed because the concept of transports didn't exist, or at least it wasn't customizable by the user and so it made sense to have it. I'm going to close this issue since it's open since quite a bit and I believe that enough explanation has been given to solve the question. Feel free to reopen if you still have any doubt

**Comment by miguelbemartin** [comment]
Could you point us to the documentation around how to setup the transport to be async?

**Comment by cleptric** [comment]
https://docs.sentry.io/platforms/php/configuration/transports/

**Comment by miguelbemartin** [comment]
Thanks @cleptric
