### ISSUE TITLE
[Monolog] 'extra' key from $record is ignored completely

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry-php#836]
Hello, i see some incompatibility in the way Monolog should be used and Sentry handler.

In monolog, there are 2 ways how to store custom informations, one is in the `extra` - https://github.com/Seldaek/monolog/blob/master/doc/01-usage.md#using-processors (usually added by preprocessors) and the `context`, usually added in the `log()` method as second argument.

At this moment `Sentry\Monolog\Handler` ignores the `$record['extra']` key completely.

I was able to solve this issue by creating monolog processor, which merges data from both:
```php
final class SentryMergeDataProcessor implements ProcessorInterface
{
    public function __invoke(array $record): array
    {
        $extra = $record['extra'] ?? [];
        $contextExtra = $record['context']['extra'] ?? [];

        $record['context']['extra'] = array_merge($extra, $contextExtra);
        $record['context']['tags'] = $record['context']['extra']['tags'] ?? [];

        unset($record['context']['extra']['tags']);

        return $record;
    }
}
```

Though i do not believe this is best practice and best possible solution. What do you think?

**Comment by JanMikes** [comment]
Anyways why this imho should be changed in official sentry monolog handler is because all monolog processors are using `extra` key internally, even for tags processor: https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/TagProcessor.php

This is why i believe it is standard in monolog and sahould be followed.

**Comment by ste93cry** [comment]
Getting the data only from `$record['context']['extra']` was done on purpose because of this quote from the [Monolog documentation](https://github.com/Seldaek/monolog/blob/master/doc/message-structure.md):

>At first glance `context` and `extra` look very similar, and they are in the sense that they both carry arbitrary data that is related to the log message somehow. The main difference is that `context` can be supplied in user land (it is the 3rd parameter to `Logger::addRecord()`) whereas `extra` is internal only and can be filled by processors. The reason processors write to `extra` and not to `context` is to prevent overriding any user provided data in `context`.

When I coded the handler I thought that what was supposed to be logged were only things added by the user. We can of course change this if we want. The only thing that makes me wonder is that processors could put everything they want into `$record['extra']`, including data that should not be logged because it's used to pass around information and/or as cache. We can be pretty sure instead that everything supplied by the user is something valuable that he wants to log supposedly

**Comment by JanMikes** [comment]
> including data that should not be logged because it's used to pass around information and/or as cache

Well, it is always up to the developer what processors he will use or not, there are no processors added automatically to the monolog logger 😄.

There are really many useful processors by default: https://github.com/Seldaek/monolog/tree/master/src/Monolog/Processor

Let's have example for future issues i might open (followed by pull requests if you are open to it):
- Git processor - could populate release
- Tag processor - should definitely be compatible with sentry tags
- Inrospection processor - possibly could be compatible with Sentry's stracktrace

I al able to send PR, also covering with tests, if you are okay with that.

**Comment by JanMikes** [comment]
For now, i have feeling from Sentry monolog handler, that i register the monolog handler but i have to configure Sentry directly in separate way, what i would love to is being able to achieve same results with monolog processors as if configuring Sentry scope/hub/options (etc user context).

**Comment by ste93cry** [comment]
As explained in other similar issues and in the comments above, a decision shared between SDKs is to avoid pulling data from unstructured logs due to the fact that blindly copying the data from there to Sentry is something dependent on the behavior expected from the user for each particular use-case and cannot be generalized easily. For this reason, I'm going to close the issue. For a better explanation the linked issues/PRs have all sort of comments on why this decision has been taken
