### ISSUE TITLE
consider nested exceptions with `excluded_exceptions`

### ISSUE THREAD

**Issue by raffomania** [getsentry/sentry-php#851]
When checking whether to ignore an exception based on the `excluded_exceptions` option, sentry only looks at the class of the outermost exception. I would expect it to also ignore any exception that contains a nested exception specified in the ignore list.

**Comment by stayallive** [comment]
Hi @raffomania, this is not something we are willing to add to the SDK since we are reporting on the outermost exception and to us it seems not logical to drop events based on their inner (previous) exceptions since those exceptions are not considered for grouping or alerting in Sentry.

You could implement this using the [`before_send`](https://github.com/getsentry/sentry-php/blob/e85c7480e41e6f417d4207a4f68dd5a09b429a63/src/Options.php#L754-L756) option if you do want this behaviour.

**Comment by Jean85** [comment]
I agree with @stayallive; FTR, the behavior was changed/fixed last in #822.

**Comment by ste93cry** [comment]
Closing as we won't change again the behavior of this option
