### ISSUE TITLE
option to disable set_error_handler method callback for notices

### ISSUE THREAD

**Issue by sankarsuda** [getsentry/sentry-php#880]
We facing performance issue with sentry as it is calling error handler callback method for all notices.

Can it be possible to disable the callback method for E_NOTICES?

One option should be helpful or you can use the error_types variable.

There is no point of capturing the notices if we are not sending the sentry.

https://github.com/getsentry/sentry-php/blob/41ef3b66c2a06e3510d6e128eec28acac388f770/src/ErrorHandler.php#L174

**Comment by Jean85** [comment]
IIRC there was a limitation for which we were forced to do that... @ste93cry maybe you remember which one it was?

**Comment by ste93cry** [comment]
Yes, it's written exactly above that line:

https://github.com/getsentry/sentry-php/blob/41ef3b66c2a06e3510d6e128eec28acac388f770/src/ErrorHandler.php#L170-L173

**Comment by Jean85** [comment]
Ok, my memory didn't fail me then..

Sorry @sankarsuda, we cannot change that.

**Comment by sankarsuda** [comment]
Ok. Thanks,

We are facing the issue after upgrading `sentry-laravel` from 0.11 to 1.2

Let me stick to 0.11 then.

**Comment by ste93cry** [comment]
But we are interested of course in the performance issue, if any. How did you found out it? If you have some data to show us we can see if we can do something, but it's kinda strange that the error handler is the culprit as it basically just collect the error data and forwards it to the integrations

**Comment by Jean85** [comment]
Well, maybe it depends on the number of generated notices?

**Comment by ste93cry** [comment]
It could be, but that would affect any error handler, be it our, of the framework, of Monolog or of whatever else. And since the error handler integration is discarding any error that does not match the `error_types` option I don't expect any severe performance issue :thinking:

**Comment by sankarsuda** [comment]
Hi @Jean85 and @ste93cry 

I could able to generate the performance issue with sentry with a simple loop with generating the multiple notices.

I have created a simple command in laravel with below code:
```php

      $start_time = microtime(true);
        for ($i = 0; $i < 10000; $i++) {
            $meta = [];

            $val        = $meta;
            $val['i2']  = $meta['customid'];
            $val['m']   = $row['message'];
            $val['i']   = $row['custom1'];
            $val['i1']  = $row['custom2'];
            $val['u']   = $row['units'];
            $val['id']  = $row['id'];
            $val['gid'] = $row['group_id'];
        }
        $end_time = microtime(true);

        // Calculate script execution time
        $execution_time = ($end_time - $start_time);

        echo " Execution time of script = " . $execution_time . " sec\n";
```

with sentry:
Execution time of script = 31.220385074615 sec

without sentry:
Execution time of script = 2.2918548583984 sec

![laravel](https://user-images.githubusercontent.com/798414/65014902-9e163a00-d93d-11e9-8049-c6c50cc217a4.png)
![sentry](https://user-images.githubusercontent.com/798414/65014904-9e163a00-d93d-11e9-8c60-24c169986cd0.png)

You can also check with xdebug enabled. I hope this helps to understand the issue

**Comment by Jean85** [comment]
@sankarsuda thanks for the profiling. Have you disabled `E_NOTICE` capturing in the example that you posted? Because I see that nearly half the time is spent in `Sentry\ErrorHandler::invokeListeners`, which by default has only this callback registered: https://github.com/getsentry/sentry-php/blob/41ef3b66c2a06e3510d6e128eec28acac388f770/src/Integration/ErrorListenerIntegration.php#L55-L81

This callback seems pretty straightforward to me, without any I/O or other heavy calls; if you set the Sentry option `error_reporting` to (at least) `E_ALL ~E_NOTICE` your execution should stop [at the if at line 76-77](https://github.com/getsentry/sentry-php/blob/41ef3b66c2a06e3510d6e128eec28acac388f770/src/Integration/ErrorListenerIntegration.php#L76-L78) so no event should be captured, and you shouldn't have a performance hit.

Can you tell me if you did set that option, and profile again if not?

**Comment by sankarsuda** [comment]
Hi @Jean85 

My Current error_reporing settings 
```error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED```

These settings are same for with and without sentry while i did the testing

**Comment by Jean85** [comment]
This is REALLY strange. Can you profile further down the `Sentry\ErrorHandler::invokeListeners` call so we can see where's the bottleneck?

**Comment by sankarsuda** [comment]
Hi @Jean85 

I have attached the screenshot with expanding the trace
![webgrind](https://user-images.githubusercontent.com/798414/65033254-40e0af80-d962-11e9-890e-84c8c88a9385.png)

I have also attached the profiler file
[cachegrind.out.58248.zip](https://github.com/getsentry/sentry-php/files/3620667/cachegrind.out.58248.zip)

**Comment by Jean85** [comment]
I've used KCacheGrind to inspect your profile, and the bottleneck is here, where `handleError` is called:

Colums: incl. time, own time, no. of class, function

![image](https://user-images.githubusercontent.com/6729988/65034860-226dba80-d948-11e9-9365-5e67d7ae4420.png)

28 of the 31 seconds of execution are spent there, and you have generated 70.001 notices in your benchmark. 28/70000=0.0004 seconds of execution per notice, so 4 tenth of a millisecond.

I don't think we can consider this a performance issue. If you have performance issues in your application due to this, I advise you to work on reducing those; as a workaround, you can patch our SDK and limit that registration, but you're warned about the possible regressions on error handling.

**Comment by sankarsuda** [comment]
Hi @Jean85 
The same benchmark executed at 2 sec without sentry and same number of times reported to laravel error handler.

Don't you think it's the issue with sentry SDK?

**Comment by sankarsuda** [comment]
Hi @Jean85 

I could able to regain my performance by setting 'default_integrations' => false
and also working as expected

**Comment by Jean85** [comment]
@sankarsuda disabling the default integrations will stop Sentry from catching errors. I'm not sure if the Laravel error handler will do that for you... @stayallive WDYT?

**Comment by sankarsuda** [comment]
@Jean85 I could able to send the errors to sentry by extending the laravel error handler as defined in https://docs.sentry.io/platforms/php/laravel/#laravel-5x

I am ok with errors reporting default.

**Comment by ste93cry** [comment]
@Jean85 disabling the default integrations will stop Sentry from catching automatically any error, exception or fatal error that happens and will also stop adding data like the HTTP request data to the event if you capture them manually.
