### ISSUE TITLE
Multiple project roots

### ISSUE THREAD

**Issue by iluuu1994** [getsentry/sentry-php#881]
Most of our non-Symfony projects have a directory structure like this:

```
project-folder/
├── foo/
├── bar/
├── baz/
├── vendor/
    ├── foo/
```

So, unfortunately we have multiple source roots. The current `project_root` option makes it impossible to specify this. There are multiple solutions to this:

* Add a `vendor_root` option to do the opposite
* Allow specifying an array of `project_root`s

Whichever one you like, I can make a pull request. Thank you!

**Comment by Jean85** [comment]
You can already use `in_app_exclude` to exclude the vendor folder, and set the root as the `project_root` option.

We need to fix the docs though, because `in_app_exclude` is marked as unavailable in the PHP SDK, which is not true: https://github.com/getsentry/sentry-php/blob/41ef3b66c2a06e3510d6e128eec28acac388f770/src/Options.php#L764

**Comment by iluuu1994** [comment]
Worked like a charm, thank you!
