### ISSUE TITLE
support for older versions of php 

### ISSUE THREAD

**Issue by parichayawalia** [getsentry/sentry-php#888]
Since raven-php got deprecated, I was trying to set up sentry-php in my project. 
However, I was unable to do so via composer since it required a >= 2.0 version of sentry/sentry, which in turn requires a PHP version upgrade from my current PHP version (7.0.9) to 7.1 or above.
Is there a way-around to set up the same with older PHP versions?

**Comment by parichayawalia** [comment]
<img width="1479" alt="Screen Shot 2019-09-25 at 9 24 36 PM" src="https://user-images.githubusercontent.com/8528614/65617629-b3910100-dfda-11e9-9272-a0c6807e3756.png">
<img width="1497" alt="Screen Shot 2019-09-25 at 9 24 11 PM" src="https://user-images.githubusercontent.com/8528614/65617630-b4299780-dfda-11e9-9786-416b21fec873.png">

**Comment by Jean85** [comment]
If you're not on PHP 7.1+, you can require the previous version, 1.x.

**Comment by ste93cry** [comment]
Closing this as we won't support PHP < `7.1` in `2.x` and newer. `1.x` is stable and although a bit old works well, if you cannot upgrade you can stay there. Also note that according to the [documentation](https://www.php.net/supported-versions.php) PHP `7.0` is not supported since the beginning of 2019, so you are using a version of the language that does not even receive security fixes. Of course I understand it may not be feasible in the immediate to upgrade it, but I strongly suggest to do it :wink:
