### ISSUE TITLE
Asynchronous client not working correctly

### ISSUE THREAD

**Issue by adiq** [getsentry/sentry-php#904]
**Problem:**
Asynchronous client is not working correctly, as SDK always wait for promise resolution. This extends response times for the user even by 3 seconds while Sentry server is down (in the default configuration).

**Cause:**
SDK has a hardcoded parameter, which makes Client wait for promise resolution: https://github.com/getsentry/sentry-php/blob/be044bfa83ff98c5dd0ea0a7ff243ff0eade721c/src/ClientBuilder.php#L352

https://github.com/getsentry/sentry-php/blob/be044bfa83ff98c5dd0ea0a7ff243ff0eade721c/src/Transport/HttpTransport.php#L110

**Additional details:**
In v2, this behaviour was possible by specifying `curl_method: async` option.

**Proposed solution:**
Allow this parameter to be configurable.

Please let me know if there is an alternative solution to that problem I am not aware of.

**Comment by ste93cry** [comment]
Yes. We may evaluate to provide (it makes a lot of sense) an "asyncronous" transport available out-of-the-box, however the sending of the events at the shutdown of the application is for sure something I would not like to support in the future as it's something that should be implemented in userland. Also, to have a fully asyncronous transport we should integrate with libraries like Swoole or ReactPHP, which I don't want to as it would add yet another dependency and a lot of code to maintain

**Comment by B-Galati** [comment]
@ste93cry FYI, Symfony http client is async by default without any event loop system like Swoole or ReactPHP.

I guess something similar could be implemented in Sentry SDK.

**Comment by Jean85** [comment]
@B-Galati that is true only if using `ext-curl`. In any case, we adopted PSR-18/HTTPlug to avoid writing and maintaining the HTTP transport layer as in the past.

**Comment by B-Galati** [comment]
You may want to reconsider this choice :p

**Comment by mfb** [comment]
PHP native streams and cURL can both send requests in parallel, which for me is the main utility of "async" requests.  It's useful for buggy apps where I'm sending out a fun mix of debug, warning and error events.  PHP native streams have one advantage which is that you can send "fire and forget" requests, where you connect and send request(s), but don't wait for a response at all, while cURL also has big advantages like HTTP/2 support.

**Comment by Jean85** [comment]
> You may want to reconsider this choice :p

Not wanting to support the HTTP layer doesn't mean not wanting to have async support in this lib. This (and related) issue(s) are here exactly because we want to give the freedom to our users to have these features; we simply cannot bear the responsibility of maintaining that complex piece of code too; a simple hook (once fixed) to flush events to Sentry servers will be more than enough in that respect.

**Comment by ste93cry** [comment]
> which for me is the main utility of "async" requests

Well, as explained in a lot of other issues/PRs async != parallel. Both the Httplug cURL client and the Guzzle client are able to send parallel requests to be honest. We are going to switch the default HTTP client to the latter because of its maturity, butusing Httplug you are not free to use whatever other library you prefer

**Comment by mfb** [comment]
Yes, it's a bit unclear what async means in these issues, but I think most folks are talking about the lack of parallel sending, unless you build your own client; this feature was called the "async" in the 1.x version.
