### ISSUE TITLE
PHP 7 incompatible with debug_backtrace()

### ISSUE THREAD

**Issue by ffw-tam-nguyen** [getsentry/sentry-php#913]
Hi everyone, 

We have issue with PHP incompatible in report when we check the site with PHP 7. 
` FILE: /var/www/docroot/sites/all/libraries/sentry-php/lib/Raven/Client.php`
```
911 | ERROR | Since PHP 7.0, functions inspecting arguments, like debug_backtrace(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$data" was changed on line 842.
     |       | (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.Changed)```

Do you have any idea on this error?

**Comment by Jean85** [comment]
What version of this library are you using? The current version (2.x) is different, and it works on PHP 7.1+ only.

**Comment by ste93cry** [comment]
From the file path it's pretty clear that the SDK version is `1.x`, however its development ceased a long time ago and apart from serious bug fixes I don't think there is someone willing to invest time in updating it to work on PHP 7+. Due to this I'm going to close this issue and my suggestion is to update to Sentry `2.x`
