### ISSUE TITLE
Add WordPress to example installation docs

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-php#93]

**Comment by stayallive** [comment]
It might be worth link to the WordPress plugins that exists instead of adding instructions?

- [WordPress Sentry Client](https://nl.wordpress.org/plugins/getsentry-client/)
- [WordPress Sentry Integration](https://github.com/stayallive/wp-sentry) (disclaimer: this is mine)

**Comment by Jean85** [comment]
I agree, but it should be clear that those are not official intergration, just suggested ones.

**Comment by stayallive** [comment]
Very much agreed.

Since instructions are the same for every other without composer (or with since WP developers are starting to use composer for their plugins/themes) php project (assuming it's integrated in a plugin or theme) I don't know what there is to explain furthur.

Did you have specific use cases in mind (if you can even remember 😜 ) @dcramer?

**Comment by stayallive** [comment]
This has been addressed and 3rd party integrations (also for WordPress) are added to the README.md.
