### ISSUE TITLE
Is 1.x branch still supported?

### ISSUE THREAD

**Issue by Quetzacoalt91** [getsentry/sentry-php#962]
Hi there,

We're looking in integrating Sentry in an existing project. Unfortunately our current PHP compatibility range includes PHP 7.0 & 5.6 which aren't supported on the main branch 2.x.

One of the solutions we have is to use the branch 1.x instead. I saw that the last release was in November 2018, but no mention of "end of life", "security only releases" or "actively supported" status.

Could you please provide some insights on this branch? Thanks

**Comment by Jean85** [comment]
PHP 5.6, 7.0 (and also 7.1) are EOL, and that's why we didn't target those in 2.0. 1.x is still functional, but it will not get any new features, and probably only critical bug fixes (which are unlikely), especially because it would be very hard to test those.

**Comment by stayallive** [comment]
Hi @Quetzacoalt91 as @Jean85 mentioned 1.x is in a working state since the latest release so you are good to use it if the environment requires it (quite a few people are still using it too without issue: https://packagist.org/packages/sentry/sentry/stats#1.10.0). 

But it will not get any new features, if a critical bug is found it will be fixed but other than that no updates are planned. It's better communicated in the docs that the client is deprecated: https://docs.sentry.io/clients/php/.

Do also keep in mind that apart from that page https://docs.sentry.io/ will always use example and refer to the new 2.x SDK.

**Comment by Quetzacoalt91** [comment]
Thank you for your replies, I'm glad to see that 1.x is still a viable solution.

**Comment by stayallive** [comment]
No problem, if there are any problems you run into or have questions feel free to open a issue so we can help you out 👍
