### ISSUE TITLE
Make it easy to use a custom HttpTransport

### ISSUE THREAD

**Issue by B-Galati** [getsentry/sentry-php#969]
Hello,

I wanted to use another HttpClient than the default one, previously it was possible with `ClientBuilder::setHttpClient()` but this method is deprecated.

I ended up doing this:

```php
        $client = HttpClient::create(['timeout' => 2]);
        $psr17Factory = new Psr17Factory();
        $httpClient = new HttplugClient($client, $psr17Factory, $psr17Factory);

        $httpPlugFactory = new HttplugFactory();
        $httpClientFactory = new HttpClientFactory(
            $httpPlugFactory,
            $httpPlugFactory,
            $httpPlugFactory,
            $httpClient,
            Client::SDK_IDENTIFIER,
            PrettyVersions::getVersion('sentry/sentry')->getPrettyVersion()
        );

        $clientBuilder->setTransportFactory(new DefaultTransportFactory($httpPlugFactory, $httpClientFactory));
```

Do you think it would be possible to find a simpler solution?

**Comment by ste93cry** [comment]
>Do you think it would be possible to find a simpler solution?

This is already the "simplified" version of what was needed to be done in the past to use a custom HTTP client because it allows you to not worry about the plugins needed to make it work with Sentry. I don't think that we can get much around this, but if you have a better solution it's welcome of course

**Comment by B-Galati** [comment]
Previously I was just doing `$clientBuilder->setHttpClient(new SentryHttpClient());`.

But this method is deprecated. Do you think it would make sense to un-deprecate it?

**Comment by ste93cry** [comment]
No it doesn't because it was a mistake to have such method on the builder as the builder should be aware only of the transport: the HTTP client is an implementation detail of the `HttpTransport` transport and the builder should know nothing about it. The new way may be more verbose, but it gives much more flexibility to the end-user while improving SRP at the cost of him having to write a bit more code than before

**Comment by B-Galati** [comment]
Thanks @ste93cry
