### ISSUE TITLE
php_uname is used without checking whether the function exists

### ISSUE THREAD

**Issue by joejansen** [getsentry/sentry-php#985]
We are migrating a Wordpress app that uses sentry-php to [Flywheel](https://getflywheel.com/). Flywheel [disables `php_uname` along with a number of other functions](https://getflywheel.com/wordpress-support/what-php-functions-are-disabled/).

In core Wordpress the use of `php_uname` is [wrapped in a check to see whether it exists](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-admin/includes/class-wp-debug-data.php#L575).

Could we do the same thing for the [use in the `ServerOsContext` class](https://github.com/getsentry/sentry-php/blob/master/src/Context/ServerOsContext.php#L182-L187)?

**Comment by ste93cry** [comment]
This really looks like a case of "security through obscurity", but I'm not a security expert so I won't judge. I'm open to change this, so if you want to submit a PR I will gladly review it. Note that the change is a bit more complicated than what it seems at a first glance as we have to ensure that an empty context is not sent at all and we cannot make the parameters and return types of the getters/setters of the `ServerOsContext` class nullable or we would break BC, so the only thing that I can think of is to set the data to an empty string and override the `isEmpty` method to work accordingly

**Comment by Jean85** [comment]
If avoiding creating the context is too complex, we could fall back to a fixed string, or use the `PHP_OS` constant, which doesn't have security implications.

**Comment by ste93cry** [comment]
>If avoiding creating the context is too complex

With the current architecture it's a bit complicated indeed, and for the future we may evaluate to (I was already thinking about this anyway) to stop creating all the contexts in the constructor of the `Event` class and instead populate them on-demand using integrations so that users can workaround these issues by disabling what they don't want/don't need. Anyway it should be feasible, we just have to accept the downside of having some messy code here and there until we find out the time to refactor this part of the codebase

>we could fall back to a fixed string

I would like to avoid this because useless and wrong data would then be reported to Sentry

>use the `PHP_OS` constant

I though about that too, but there are two issues: the first one is that we should parse ourselves the value to extract each single information, and the second one (and most important) is that this constant returns the details of the OS PHP was built on, which is different from `php_uname` that returns instead the details of the current OS

**Comment by fuzzy76** [comment]
> In core Wordpress the use of `php_uname` is [wrapped in a check to see whether it exists](https://core.trac.wordpress.org/browser/tags/5.3/src/wp-admin/includes/class-wp-debug-data.php#L575).

Wow. That Wordpress file looks like a nightmare, checking every single core function they use down the sourcecode... Are you sure that stuff should be encouraged?

**Comment by ste93cry** [comment]
>Are you sure that stuff should be encouraged?

My opinion is that it should not, but WordPress runs on a myriad of servers, environments, etc and so I think that they are obliged to do this to avoid breaking websites as most as possible
