### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by viksts** [getsentry/sentry-php#987]
Hi,
I am trying to upgrade my sentry version to 2.2.6. However when i am doing
composer update 
its giving error `sentry/sentry 2.2.6 requires php-http/async-client-implementation ^1.0 -> no matching package found.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
`
How do i solve it.

**Comment by stayallive** [comment]
Hi @viksts we're you on version `1.x` before?

---

If that's the case it's you might want to take look at the [upgrade docs](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md) and/or the new [documentation](https://docs.sentry.io/platforms/php/) on how to get started.

Basically we now require a HTTP client to be supplied by the user if `sentry/sentry` is required, that's why we created the `sentry/sdk` package. The `sentry/sdk` package comes with a client out of the box.

You can install it by doing:
```
composer remove sentry/sentry
composer require sentry/sdk
```

---

If that's not the case, could you please share your `composer.json` and share your PHP version so we can investigate further?

**Comment by viksts** [comment]
Hi,
i have update to sentry :- 2.0.0 through composer require sentry/sdk:2.0 but now i am getting Raven_client class not found.

**Comment by stayallive** [comment]
Hi @viksts, as mentioned:

> And remember to check out the [upgrade docs](https://github.com/getsentry/sentry-php/blob/master/UPGRADE-2.0.md) and new [documentation](https://docs.sentry.io/platforms/php/) since a lot has changed from `1.x` to `2.x`.

Version `2.x` is a complete rewrite, so it's not a "simple" upgrade and requires some work from you part to update you application to use the correct classes.

If you are not ready for that yet you can pin you `sentry/sentry` dependency to `^1.11` (`composer require "sentry/sentry:^1.11"`), if you do that you should remove `sentry/sdk` dependency first (`composer remove sentry/sdk`) since the `sentry/sdk` package is only for the `2.x` version.

**Comment by viksts** [comment]
Ok, previously i was using sentry/sentry :1.10.0 but it has php deprecation error `Array and string offset access syntax with curly braces is deprecated` and we are upgrading php version of project to 7.4 that's why i have to upgrade the sentry version. So if you are saying to use sentry/sentry:1.11.0 then my question is that deprecation error got fixed in version 1.11.0?

**Comment by stayallive** [comment]
Ahh, I understand now! Yeah we released 1.11 a few weeks ago to fix those errors: https://github.com/getsentry/sentry-php/releases/tag/1.11.0.

**Comment by viksts** [comment]
> 
> 
> Ahh, I understand now! Yeah we released 1.11 a few weeks ago to fix those errors: https://github.com/getsentry/sentry-php/releases/tag/1.11.0.

OOH, So i can keep it on version 1.10.0 correct?

**Comment by stayallive** [comment]
No, `1.11.0` than, but that was probably what you meant ;) 

So yes `1.11.0` should not have any problems on PHP `7.4`.

**Comment by viksts** [comment]
> 
> 
> No, `1.11.0`, but that was probably what you meant 😉
> 
> So yes `1.11.0` should not have any problems on PHP `7.4`.

Thanks bro you save my day.

**Comment by stayallive** [comment]
No problem, let us know if you still run into issues!

**Comment by ste93cry** [comment]
I suggest anyway to update to the latest `2.*` version as it's being actively tested and maintained, especially on PHP 7, while `1.x` is not (we accept bug fixes but no really active development is done on it)
