### ISSUE TITLE
Replace guzzlehttp/psr7 with nyholm/psr7 

### ISSUE THREAD

**Issue by garak** [getsentry/sentry-php#992]
It looks like the latter is better (according to [benchmarks](https://github.com/Nyholm/psr7) published by its author).
I can provide a PR, if needed.

**Comment by ste93cry** [comment]
We switched recently from `zendframework/zend-diactoros` to `guzzlehttp/psr7`, we now use Guzzle as HTTP client out-of-the-box in `getsentry/sentry-php-sdk` and in reality in this package we depend strictly on the latter just for the `RequestIntegration` if I'm not wrong. If you prefer to use another package as factory for the HTTP requests there is always the possibility of customizing the instantiation of the SDK, thus I don't really see any pro in changing one more time library

**Comment by garak** [comment]
Well, the pros are just in benchmarks linked above.
I'm already using another package, but unfortunately this one is hard-coded in this library.

**Comment by ste93cry** [comment]
As I said, I understand that the package you linked may be better performance-wise, but making another switch two months after the last one only for this reason is not enough for me. Also, as I said the library is indeed a dependency of this project, but it's used just to extract data from the server request, thus I'm not sure about which performance penalties we are talking about. You could want to improve the performances when using it to send the event to the server, but I already explained that for that there is nothing hardcoded that uses `guzzlehttp/psr7`, so you can just customize the SDK initialization and set whatever PSR-7 factory you like most

**Comment by garak** [comment]
Probably I'm missing something, but I don't see how I can force library to use a different psr7 [here](https://github.com/getsentry/sentry-php/blob/master/src/Integration/RequestIntegration.php#L101).

I see, instead, the possibility to improve that part, looking for all possible psr7 implementations and using the first found.

**Comment by ste93cry** [comment]
>the possibility to improve that part, looking for all possible psr7 implementations and using the first found

The PR allowing this has been merged yesterday in `develop`, take a look at the `RequestFetcherInterface`. You will have to instantiate the integration yourself though, and pass whichever PSR-17 factory you want

**Comment by garak** [comment]
Ah, that's cool.
But I see that such PR doesn't remove `use GuzzleHttp\Psr7\ServerRequest;`...

**Comment by ste93cry** [comment]
I saw that, but to me it looks like a leftover of the cleanup :thinking:  Nothing to worry about though, I will remove it as soon as I open the next PR, or you can contribute the change if you want, I will gladly accept it

**Comment by garak** [comment]
Thank you very much for your support.
