### ISSUE TITLE
Scope::setContext can only be called with data

### ISSUE THREAD

**Issue by codegain** [getsentry/sentry-php#993]
Hi,

I observed that calling `$scope->setContext('context', []);` results in the following error on the web interface: 

```
There was 1 error encountered while processing this event
contexts.context: Discarded invalid value
Reason expected an object
Value []
```

My code would be:
```
[...]
// Add some extra data to the event
$scope->setContext('context', $record['context'] ?? []);

$this->hub->captureEvent($eventData);
```

My current workaround is to not call `setContext` if the value is an empty array:

```
[...]
// Add some extra data to the event
if (!empty($record['context'])) {
     $scope->setContext('context', $record['context']);
}
$this->hub->captureEvent($eventData);
```

I guess this is due to some JSON encoding which sends the empty php array as `[]` instead of `{}`.

**Comment by ste93cry** [comment]
>I guess this is due to some JSON encoding which sends the empty php array as `[]` instead of `{}`.

This is definitely the issue, but we cannot really do anything about it as in PHP there is no way to serialize an empty array as an object if you don't cast it manually. The constant `JSON_FORCE_OBJECT` cannot help us as it would act on every empty array instead of the ones you selectively want to cast and there was no strong consensus on enforcing the `object` typehinting on the argument of the `Scope::setContext` method instead of an array which still works in case you have an hashmap. The only thing that was added is the docblock saying that we expect an `array<string, mixed>`, thus if you use a static analysis tool it should be able to help you getting it right

**Comment by codegain** [comment]
I see. My static analysis is not showing any errors because an empty array still matches `array<string, mixed>` so it assumes this is an expected value.

Would it be an option to fix this on the server-side? Treat the value `[]` as `{}` in this case?

**Comment by ste93cry** [comment]
>Would it be an option to fix this on the server-side? Treat the value [] as {} in this case?

I don't think it would be correct to fix this server-side as the API contract is right in expecting an hashmap instead of a list (which is basically an empty array in PHP), but I don't see any reason about why it should not be possible. I suggest to workaround the issue in your code or open a new issue in [`getsentry/sentry`](https://github.com/getsentry/sentry)

**Comment by codegain** [comment]
@ste93cry Thanks for the explanation. For now I will use my workaround but I also opened a new issue in https://github.com/getsentry/sentry.

**Comment by untitaker** [comment]
Why can't contexts be cast into object all the time? No other JSON type is valid.

**Comment by ste93cry** [comment]
>No other JSON type is valid

This is true only for the root key of the event (the `context` key), but for each entry of the context itself the value can be anything from a `string` to a `list`. This is perfectly valid, isn't it?

```
event.context {
    foo: "bar",
    bar: ["foo"],
    "baz": {
        "qux": "quux"
    }
}
```

The constant mentioned above is a setting for the `json_encode` function which converts all empty arrays to objects, regardless of at which depth they are in the data passed to the function

**Comment by untitaker** [comment]
I don't know anything about PHP. This is invalid, and if you add anything into the array it's also invalid:

```
{"contexts": {"foo": []}}
```

So all the contexts but `baz` in your example are invalid.

That is, right now on sentry.io. Maybe we are talking about different Sentry versions?

**Comment by ste93cry** [comment]
Sorry, what I meant was that `event.context` was a single context. The correct example would have been

```json
{
    "contexts": {
        "context": {
            "foo": "bar",
            "bar": [],
            "baz": {
                "qux": "quux"
            }
        }
    }
}
```

Using `JSON_FORCE_OBJECT` would cast `[]` to `{}` because it cast all empty arrays to objects

**Comment by untitaker** [comment]
Sure.

What about this one from the OP:

```php
$scope->setContext('context', $record['context'] ?? []);
```

This would define `{"contexts": {"context": []}}`. Is the suggestion that we coerce this into `{}`?

**Comment by codegain** [comment]
> This would define `{"contexts": {"context": []}}`. Is the suggestion that we coerce this into `{}`?

@untitaker That's what I thought about. If the context is just simply an empty array, this could be turned into `{}`.
Like

```
if (empty($value)) {
   $value = new \stdClass();
}
$this->value = $value;
```

in the `->setContext` method (check for `empty` would be enough because only arrays can be passed as argument).

**Comment by ste93cry** [comment]
Wouldn't it makes more sense to simply avoid sending an empty context?
